INSERT INTO Item_Addons (name, category_id, rarity_id, icon) VALUES
-- Flashlights Add-ons (category_id: 1)
('Battery', 1, 1, 'assets/img/survivor/item/addon/battery.png'),
('Leather Grip', 1, 1, 'assets/img/survivor/item/addon/leather_grip.png'),
('Power Bulb', 1, 1, 'assets/img/survivor/item/addon/power_bulb.png'),
('Wide Lens', 1, 1, 'assets/img/survivor/item/addon/wide_lens.png'),
('Focus Lens', 1, 2, 'assets/img/survivor/item/addon/focus_lens.png'),
('Heavy Duty Battery', 1, 2, 'assets/img/survivor/item/addon/heavy_duty_battery.png'),
('Low Amp Filament', 1, 2, 'assets/img/survivor/item/addon/low_amp_filament.png'),
('Rubber Grip', 1, 2, 'assets/img/survivor/item/addon/rubber_grip.png'),
('TIR Optic', 1, 2, 'assets/img/survivor/item/addon/tir_optic.png'),
('Intense Halogen', 1, 3, 'assets/img/survivor/item/addon/intense_halogen.png'),
('Long Life Battery', 1, 3, 'assets/img/survivor/item/addon/long_life_battery.png'),
('High-End Sapphire Lens', 1, 4, 'assets/img/survivor/item/addon/high_end_sapphire_lens.png'),
('Odd Bulb', 1, 5, 'assets/img/survivor/item/addon/odd_bulb.png'),
-- Med-Kits Add-ons (category_id: 2)
('Bandages', 2, 1, 'assets/img/survivor/item/addon/bandages.png'),
('Butterfly Tape', 2, 1, 'assets/img/survivor/item/addon/butterfly_tape.png'),
('Rubber Gloves', 2, 1, 'assets/img/survivor/item/addon/rubber_gloves.png'),
('Medical Scissors', 2, 2, 'assets/img/survivor/item/addon/medical_scissors.png'),
('Needle & Thread', 2, 2, 'assets/img/survivor/item/addon/needle_thread.png'),
('Self Adherent Wrap', 2, 2, 'assets/img/survivor/item/addon/self_adherent_wrap.png'),
('Sponge', 2, 2, 'assets/img/survivor/item/addon/sponge.png'),
('Gauze Roll', 2, 3, 'assets/img/survivor/item/addon/gauze_roll.png'),
('Surgical Suture', 2, 3, 'assets/img/survivor/item/addon/surgical_suture.png'),
('Abdominal Dressing', 2, 4, 'assets/img/survivor/item/addon/abdominal_dressing.png'),
('Styptic Agent', 2, 4, 'assets/img/survivor/item/addon/styptic_agent.png'),
('Anti-Haemorrhagic Syringe', 2, 5, 'assets/img/survivor/item/addon/anti_haemorrhagic_syringe.png'),
('Gel Dressings', 2, 5, 'assets/img/survivor/item/addon/gel_dressings.png'),
-- Toolboxes Add-ons (category_id: 3)
('Clean Rag', 3, 1, 'assets/img/survivor/item/addon/clean_rag.png'),
('Instructions', 3, 1, 'assets/img/survivor/item/addon/instructions.png'),
('Scraps', 3, 1, 'assets/img/survivor/item/addon/scraps.png'),
('Cutting Wire', 3, 2, 'assets/img/survivor/item/addon/cutting_wire.png'),
('Protective Gloves', 3, 2, 'assets/img/survivor/item/addon/protective_gloves.png'),
('Socket Swivels', 3, 2, 'assets/img/survivor/item/addon/socket_swivels.png'),
('Spring Clamp', 3, 2, 'assets/img/survivor/item/addon/spring_clamp.png'),
('Wire Spool', 3, 2, 'assets/img/survivor/item/addon/wire_spool.png'),
('Grip Wrench', 3, 3, 'assets/img/survivor/item/addon/grip_wrench.png'),
('Hacksaw', 3, 3, 'assets/img/survivor/item/addon/hacksaw.png'),
('Brand New Part', 3, 5, 'assets/img/survivor/item/addon/brand_new_part.png'),
-- Keys Add-ons (category_id: 4)
('Prayer Rope', 4, 1, 'assets/img/survivor/item/addon/prayer_rope.png'),
('Eroded Token', 4, 2, 'assets/img/survivor/item/addon/eroded_token.png'),
('Prayer Beads', 4, 2, 'assets/img/survivor/item/addon/prayer_beads.png'),
('Scratched Pearl', 4, 2, 'assets/img/survivor/item/addon/scratched_pearl.png'),
('Gold Token', 4, 3, 'assets/img/survivor/item/addon/gold_token.png'),
('Blood Amber', 4, 4, 'assets/img/survivor/item/addon/blood_amber.png'),
('Milky Glass', 4, 4, 'assets/img/survivor/item/addon/milky_glass.png'),
('Unique Wedding Ring', 4, 4, 'assets/img/survivor/item/addon/unique_wedding_ring.png'),
('Weaved Ring', 4, 4, 'assets/img/survivor/item/addon/weaved_ring.png'),
-- Maps Add-ons (category_id: 5)
('Map Addendum', 5, 1, 'assets/img/survivor/item/addon/map_addendum.png'),
('Glass Bead', 5, 2, 'assets/img/survivor/item/addon/glass_bead.png'),
('Red Twine', 5, 2, 'assets/img/survivor/item/addon/red_twine.png'),
('Retardant Jelly', 5, 2, 'assets/img/survivor/item/addon/retardant_jelly.png'),
('Unusual Stamp', 5, 2, 'assets/img/survivor/item/addon/unusual_stamp.png'),
('Yellow Wire', 5, 2, 'assets/img/survivor/item/addon/yellow_wire.png'),
('Black Silk Cord', 5, 3, 'assets/img/survivor/item/addon/black_silk_cord.png'),
('Odd Stamp', 5, 3, 'assets/img/survivor/item/addon/odd_stamp.png'),
('Crystal Bead', 5, 4, 'assets/img/survivor/item/addon/crystal_bead.png');