
-- Rarity values: Common, Uncommon, Rare, Very Rare, Ultra Rare

INSERT INTO Killer_Addons (name, killer_id, rarity_id, icon) VALUES
-- The Trapper (Evan MacMillan, ID: 1)
('Trapper Sack', 1, 'Common', 'assets/img/killer/addon/trapper_sack.png'),
('Trapper Gloves', 1, 'Uncommon', 'assets/img/killer/addon/trapper_gloves.png'),
('Bear Oil', 1, 'Uncommon', 'assets/img/killer/addon/bear_oil.png'),
('Padded Jaws', 1, 'Common', 'assets/img/killer/addon/padded_jaws.png'),
('Serrated Jaws', 1, 'Rare', 'assets/img/killer/addon/serrated_jaws.png'),
('Wax Brick', 1, 'Uncommon', 'assets/img/killer/addon/wax_brick.png'),
('4-Coil Spring Kit', 1, 'Rare', 'assets/img/killer/addon/4_coil_spring_kit.png'),
('Trapper Bag', 1, 'Rare', 'assets/img/killer/addon/trapper_bag.png'),
('Logwood Dye', 1, 'Uncommon', 'assets/img/killer/addon/logwood_dye.png'),
('Secondary Coil', 1, 'Rare', 'assets/img/killer/addon/secondary_coil.png'),
('Rusted Jaws', 1, 'Rare', 'assets/img/killer/addon/rusted_jaws.png'),
('Fastening Tools', 1, 'Very Rare', 'assets/img/killer/addon/fastening_tools.png'),
('Tar Bottle', 1, 'Rare', 'assets/img/killer/addon/tar_bottle.png'),
('Oily Coil', 1, 'Very Rare', 'assets/img/killer/addon/oily_coil.png'),
('Honing Stone', 1, 'Very Rare', 'assets/img/killer/addon/honing_stone.png'),
('Diamond Stone', 1, 'Ultra Rare', 'assets/img/killer/addon/diamond_stone.png'),
('Bloody Coil', 1, 'Very Rare', 'assets/img/killer/addon/bloody_coil.png'),
('Iridescent Stone', 1, 'Ultra Rare', 'assets/img/killer/addon/iridescent_stone.png'),
('Tension Spring', 1, 'Rare', 'assets/img/killer/addon/tension_spring.png'),
('Coffee Grounds', 1, 'Uncommon', 'assets/img/killer/addon/coffee_grounds.png'),

-- The Wraith (Philip Ojomo, ID: 2)
('The Serpent - Soot', 2, 'Common', 'assets/img/killer/addon/serpent_soot.png'),
('The Hound - Soot', 2, 'Common', 'assets/img/killer/addon/hound_soot.png'),
('The Ghost - Soot', 2, 'Rare', 'assets/img/killer/addon/ghost_soot.png'),
('The Beast - Soot', 2, 'Common', 'assets/img/killer/addon/beast_soot.png'),
('Blind Warrior - Mud', 2, 'Uncommon', 'assets/img/killer/addon/blind_warrior_mud.png'),
('Shadow Dance - White', 2, 'Uncommon', 'assets/img/killer/addon/shadow_dance_white.png'),
('Blink - Mud', 2, 'Common', 'assets/img/killer/addon/blink_mud.png'),
('Windstorm - Mud', 2, 'Uncommon', 'assets/img/killer/addon/windstorm_mud.png'),
('Swift Hunt - Mud', 2, 'Uncommon', 'assets/img/killer/addon/swift_hunt_mud.png'),
('Blink - White', 2, 'Rare', 'assets/img/killer/addon/blink_white.png'),
('Windstorm - White', 2, 'Rare', 'assets/img/killer/addon/windstorm_white.png'),
('Swift Hunt - White', 2, 'Rare', 'assets/img/killer/addon/swift_hunt_white.png'),
('Shadow Dance - Blood', 2, 'Rare', 'assets/img/killer/addon/shadow_dance_blood.png'),
('Coxcombed Clapper', 2, 'Very Rare', 'assets/img/killer/addon/coxcombed_clapper.png'),
('All Seeing - Blood', 2, 'Very Rare', 'assets/img/killer/addon/all_seeing_blood.png'),
('Bone Clapper', 2, 'Rare', 'assets/img/killer/addon/bone_clapper.png'),
('All Seeing - Spirit', 2, 'Ultra Rare', 'assets/img/killer/addon/all_seeing_spirit.png'),
('Swift Hunt - Blood', 2, 'Very Rare', 'assets/img/killer/addon/swift_hunt_blood.png'),
('Windstorm - Blood', 2, 'Very Rare', 'assets/img/killer/addon/windstorm_blood.png'),
('Blink - Blood', 2, 'Very Rare', 'assets/img/killer/addon/blink_blood.png'),

-- The Hillbilly (Max Thompson Jr., ID: 3)
('Steel Toe Boots', 3, 'Common', 'assets/img/killer/addon/steel_toe_boots.png'),
('Junkyard Air Filter', 3, 'Common', 'assets/img/killer/addon/junkyard_air_filter.png'),
('Dad’s Boots', 3, 'Uncommon', 'assets/img/killer/addon/dads_boots.png'),
('Spiked Boots', 3, 'Rare', 'assets/img/killer/addon/spiked_boots.png'),
('High-Speed Idler Screw', 3, 'Uncommon', 'assets/img/killer/addon/high_speed_idler_screw.png'),
('Counterweight', 3, 'Uncommon', 'assets/img/killer/addon/counterweight.png'),
('Cracked Primer Bulb', 3, 'Rare', 'assets/img/killer/addon/cracked_primer_bulb.png'),
('Big Buckle', 3, 'Common', 'assets/img/killer/addon/big_buckle.png'),
('Begrimed Chains', 3, 'Very Rare', 'assets/img/killer/addon/begrimed_chains.png'),
('Apex Muffler', 3, 'Rare', 'assets/img/killer/addon/apex_muffler.png'),
('Thompson’s Mix', 3, 'Uncommon', 'assets/img/killer/addon/thompsons_mix.png'),
('Death Engravings', 3, 'Rare', 'assets/img/killer/addon/death_engravings.png'),
('Doom Engravings', 3, 'Very Rare', 'assets/img/killer/addon/doom_engravings.png'),
('Low Kickback Chains', 3, 'Rare', 'assets/img/killer/addon/low_kickback_chains.png'),
('LoPro Chains', 3, 'Very Rare', 'assets/img/killer/addon/lopro_chains.png'),
('Iridescent Brick', 3, 'Ultra Rare', 'assets/img/killer/addon/iridescent_brick.png'),
('Greasy Black Lens', 3, 'Rare', 'assets/img/killer/addon/greasy_black_lens.png'),
('Pighouse Gloves', 3, 'Very Rare', 'assets/img/killer/addon/pighouse_gloves.png'),
('Infrared Scope', 3, 'Ultra Rare', 'assets/img/killer/addon/infrared_scope.png'),
('Tuned Carburettor', 3, 'Very Rare', 'assets/img/killer/addon/tuned_carburettor.png'),

-- The Nurse (Sally Smithson, ID: 4)
('Wooden Horse', 4, 'Common', 'assets/img/killer/addon/wooden_horse.png'),
('White Nit Comb', 4, 'Common', 'assets/img/killer/addon/white_nit_comb.png'),
('Torn Bookmark', 4, 'Uncommon', 'assets/img/killer/addon/torn_bookmark.png'),
('Metal Spoon', 4, 'Common', 'assets/img/killer/addon/metal_spoon.png'),
('Bad Man’s Keepsake', 4, 'Uncommon', 'assets/img/killer/addon/bad_mans_keepsake.png'),
('Plaid Flannel', 4, 'Uncommon', 'assets/img/killer/addon/plaid_flannel.png'),
('Dull Bracelet', 4, 'Common', 'assets/img/killer/addon/dull_bracelet.png'),
('Anxious Gasp', 4, 'Rare', 'assets/img/killer/addon/anxious_gasp.png'),
('Fragile Wheeze', 4, 'Rare', 'assets/img/killer/addon/fragile_wheeze.png'),
('Spasmodic Breath', 4, 'Very Rare', 'assets/img/killer/addon/spasmodic_breath.png'),
('Heavy Panting', 4, 'Rare', 'assets/img/killer/addon/heavy_panting.png'),
('Ataxic Respiration', 4, 'Uncommon', 'assets/img/killer/addon/ataxic_respiration.png'),
('Kavanagh’s Last Breath', 4, 'Very Rare', 'assets/img/killer/addon/kavanaghs_last_breath.png'),
('Jenner’s Last Breath', 4, 'Very Rare', 'assets/img/killer/addon/jenners_last_breath.png'),
('Campbell’s Last Breath', 4, 'Rare', 'assets/img/killer/addon/campbells_last_breath.png'),
('Bad Man’s Last Breath', 4, 'Very Rare', 'assets/img/killer/addon/bad_mans_last_breath.png'),
('Matchbox', 4, 'Ultra Rare', 'assets/img/killer/addon/matchbox.png'),
('Iridescent Pendant', 4, 'Ultra Rare', 'assets/img/killer/addon/iridescent_pendant.png'),
('Breath of the Void', 4, 'Very Rare', 'assets/img/killer/addon/breath_of_the_void.png'),
('Dark Cincture', 4, 'Rare', 'assets/img/killer/addon/dark_cincture.png'),

-- The Shape (Michael Myers, ID: 5)
('Tacky Earrings', 5, 'Common', 'assets/img/killer/addon/tacky_earrings.png'),
('Boyfriend’s Memo', 5, 'Common', 'assets/img/killer/addon/boyfriends_memo.png'),
('Blond Hair', 5, 'Uncommon', 'assets/img/killer/addon/blond_hair.png'),
('Reflective Fragment', 5, 'Uncommon', 'assets/img/killer/addon/reflective_fragment.png'),
('Memorial Flower', 5, 'Common', 'assets/img/killer/addon/memorial_flower.png'),
('Vanity Mirror', 5, 'Very Rare', 'assets/img/killer/addon/vanity_mirror.png'),
('Scratched Mirror', 5, 'Very Rare', 'assets/img/killer/addon/scratched_mirror.png'),
('Lock of Hair', 5, 'Rare', 'assets/img/killer/addon/lock_of_hair.png'),
('Judith’s Journal', 5, 'Rare', 'assets/img/killer/addon/judiths_journal.png'),
('Hair Bow', 5, 'Uncommon', 'assets/img/killer/addon/hair_bow.png'),
('Glass Fragment', 5, 'Common', 'assets/img/killer/addon/glass_fragment.png'),
('Dead Rabbit', 5, 'Rare', 'assets/img/killer/addon/dead_rabbit.png'),
('Mirror Shard', 5, 'Rare', 'assets/img/killer/addon/mirror_shard.png'),
('Jewelry', 5, 'Uncommon', 'assets/img/killer/addon/jewelry.png'),
('Jewelry Box', 5, 'Rare', 'assets/img/killer/addon/jewelry_box.png'),
('J. Myers Memorial', 5, 'Rare', 'assets/img/killer/addon/j_myers_memorial.png'),
('Tombstone Piece', 5, 'Very Rare', 'assets/img/killer/addon/tombstone_piece.png'),
('Fragrant Tuft of Hair', 5, 'Ultra Rare', 'assets/img/killer/addon/fragrant_tuft_of_hair.png'),
('Iridescent Seal', 5, 'Ultra Rare', 'assets/img/killer/addon/iridescent_seal.png'),
('Judith’s Tombstone', 5, 'Ultra Rare', 'assets/img/killer/addon/judiths_tombstone.png'),

-- The Hag (Lisa Sherwood, ID: 6)
('Rope Necklet', 6, 'Common', 'assets/img/killer/addon/rope_necklet.png'),
('Powdered Eggshell', 6, 'Common', 'assets/img/killer/addon/powdered_eggshell.png'),
('Dead Fly Mud', 6, 'Common', 'assets/img/killer/addon/dead_fly_mud.png'),
('Bog Water', 6, 'Uncommon', 'assets/img/killer/addon/bog_water.png'),
('Bloodied Water', 6, 'Rare', 'assets/img/killer/addon/bloodied_water.png'),
('Cracked Turtle Egg', 6, 'Uncommon', 'assets/img/killer/addon/cracked_turtle_egg.png'),
('Pussy Willow', 6, 'Uncommon', 'assets/img/killer/addon/pussy_willow.png'),
('Half Eggshell', 6, 'Common', 'assets/img/killer/addon/half_eggshell.png'),
('Dragonfly Wings', 6, 'Uncommon', 'assets/img/killer/addon/dragonfly_wings.png'),
('Cypress Necklet', 6, 'Common', 'assets/img/killer/addon/cypress_necklet.png'),
('Swamp Orchid Necklet', 6, 'Uncommon', 'assets/img/killer/addon/swamp_orchid_necklet.png'),
('Willow Wreath', 6, 'Rare', 'assets/img/killer/addon/willow_wreath.png'),
('Bloodied Mud', 6, 'Very Rare', 'assets/img/killer/addon/bloodied_mud.png'),
('Granma’s Heart', 6, 'Very Rare', 'assets/img/killer/addon/granmas_heart.png'),
('Disfigured Ear', 6, 'Rare', 'assets/img/killer/addon/disfigured_ear.png'),
('Rusty Shackles', 6, 'Very Rare', 'assets/img/killer/addon/rusty_shackles.png'),
('Mint Rag', 6, 'Ultra Rare', 'assets/img/killer/addon/mint_rag.png'),
('Iridescent Flesh', 6, 'Ultra Rare', 'assets/img/killer/addon/iridescent_flesh.png'),
('Scarred Hand', 6, 'Very Rare', 'assets/img/killer/addon/scarred_hand.png'),
('Cracked Shell', 6, 'Rare', 'assets/img/killer/addon/cracked_shell.png'),

-- The Doctor (Herman Carter, ID: 7)
('Mouldy Electrode', 7, 'Common', 'assets/img/killer/addon/mouldy_electrode.png'),
('Maple Knight', 7, 'Common', 'assets/img/killer/addon/maple_knight.png'),
('Order - Class I', 7, 'Common', 'assets/img/killer/addon/order_class_i.png'),
('Calm - Class I', 7, 'Common', 'assets/img/killer/addon/calm_class_i.png'),
('Discipline - Class II', 7, 'Uncommon', 'assets/img/killer/addon/discipline_class_ii.png'),
('Order - Class II', 7, 'Uncommon', 'assets/img/killer/addon/order_class_ii.png'),
('Calm - Class II', 7, 'Uncommon', 'assets/img/killer/addon/calm_class_ii.png'),
('Polished Electrode', 7, 'Uncommon', 'assets/img/killer/addon/polished_electrode.png'),
('Restraint - Class II', 7, 'Uncommon', 'assets/img/killer/addon/restraint_class_ii.png'),
('Discipline - Class III', 7, 'Rare', 'assets/img/killer/addon/discipline_class_iii.png'),
('Order - Carter’s Notes', 7, 'Rare', 'assets/img/killer/addon/order_carters_notes.png'),
('Calm - Carter’s Notes', 7, 'Rare', 'assets/img/killer/addon/calm_carters_notes.png'),
('Restraint - Carter’s Notes', 7, 'Rare', 'assets/img/killer/addon/restraint_carters_notes.png'),
('High Stimulus Electrode', 7, 'Rare', 'assets/img/killer/addon/high_stimulus_electrode.png'),
('Interview Tape', 7, 'Very Rare', 'assets/img/killer/addon/interview_tape.png'),
('Obedience - Carter’s Notes', 7, 'Very Rare', 'assets/img/killer/addon/obedience_carters_notes.png'),
('Iridescent King', 7, 'Ultra Rare', 'assets/img/killer/addon/iridescent_king.png'),
('Iridescent Queen', 7, 'Ultra Rare', 'assets/img/killer/addon/iridescent_queen.png'),
('Scrapped Tape', 7, 'Rare', 'assets/img/killer/addon/scrapped_tape.png'),
('Discipline - Carter’s Notes', 7, 'Very Rare', 'assets/img/killer/addon/discipline_carters_notes.png'),

-- The Huntress (Anna, ID: 8)
('Leather Loop', 8, 'Common', 'assets/img/killer/addon/leather_loop.png'),
('Coarse Stone', 8, 'Common', 'assets/img/killer/addon/coarse_stone.png'),
('Bandaged Haft', 8, 'Common', 'assets/img/killer/addon/bandaged_haft.png'),
('Amanita Toxin', 8, 'Uncommon', 'assets/img/killer/addon/amanita_toxin.png'),
('Yew Seed Brew', 8, 'Uncommon', 'assets/img/killer/addon/yew_seed_brew.png'),
('Shiny Pin', 8, 'Uncommon', 'assets/img/killer/addon/shiny_pin.png'),
('Oak Haft', 8, 'Uncommon', 'assets/img/killer/addon/oak_haft.png'),
('Manna Grass Braid', 8, 'Common', 'assets/img/killer/addon/manna_grass_braid.png'),
('Deerskin Gloves', 8, 'Rare', 'assets/img/killer/addon/deerskin_gloves.png'),
('Yew Seed Concoction', 8, 'Rare', 'assets/img/killer/addon/yew_seed_concoction.png'),
('Venomous Concoction', 8, 'Rare', 'assets/img/killer/addon/venomous_concoction.png'),
('Flower Babushka', 8, 'Rare', 'assets/img/killer/addon/flower_babushka.png'),
('Glowing Concoction', 8, 'Very Rare', 'assets/img/killer/addon/glowing_concoction.png'),
('Infantry Belt', 8, 'Very Rare', 'assets/img/killer/addon/infantry_belt.png'),
('Begrimed Head', 8, 'Very Rare', 'assets/img/killer/addon/begrimed_head.png'),
('Iridescent Head', 8, 'Ultra Rare', 'assets/img/killer/addon/iridescent_head.png'),
('Soldier’s Puttee', 8, 'Very Rare', 'assets/img/killer/addon/soldiers_puttee.png'),
('Berus Toxin', 8, 'Rare', 'assets/img/killer/addon/berus_toxin.png'),
('Rose Root', 8, 'Rare', 'assets/img/killer/addon/rose_root.png'),
('Wooden Fox', 8, 'Very Rare', 'assets/img/killer/addon/wooden_fox.png'),

-- The Cannibal (Bubba Sawyer, ID: 9)
('Chainsaw File', 9, 'Common', 'assets/img/killer/addon/chainsaw_file.png'),
('Vegetable Oil', 9, 'Common', 'assets/img/killer/addon/vegetable_oil.png'),
('Spark Plug', 9, 'Uncommon', 'assets/img/killer/addon/spark_plug.png'),
('Speed Limiter', 9, 'Common', 'assets/img/killer/addon/speed_limiter.png'),
('Shop Lubricant', 9, 'Uncommon', 'assets/img/killer/addon/shop_lubricant.png'),
('Primer Bulb', 9, 'Rare', 'assets/img/killer/addon/primer_bulb.png'),
('Long Guide Bar', 9, 'Uncommon', 'assets/img/killer/addon/long_guide_bar.png'),
('Knife Scratches', 9, 'Uncommon', 'assets/img/killer/addon/knife_scratches.png'),
('Homemade Muffler', 9, 'Rare', 'assets/img/killer/addon/homemade_muffler.png'),
('Chilli', 9, 'Rare', 'assets/img/killer/addon/chilli.png'),
('The Grease', 9, 'Rare', 'assets/img/killer/addon/the_grease.png'),
('The Beast’s Marks', 9, 'Rare', 'assets/img/killer/addon/the_beasts_marks.png'),
('Ragged Engine', 9, 'Very Rare', 'assets/img/killer/addon/ragged_engine.png'),
('Depth Gauge Rake', 9, 'Rare', 'assets/img/killer/addon/depth_gauge_rake.png'),
('Award-Winning Chilli', 9, 'Very Rare', 'assets/img/killer/addon/award_winning_chilli.png'),
('Carburetor Tuning Guide', 9, 'Very Rare', 'assets/img/killer/addon/carburetor_tuning_guide.png'),
('Iridescent Flesh', 9, 'Ultra Rare', 'assets/img/killer/addon/iridescent_flesh_cannibal.png'),
('Begrimed Chains', 9, 'Very Rare', 'assets/img/killer/addon/begrimed_chains_cannibal.png'),
('Light Chassis', 9, 'Rare', 'assets/img/killer/addon/light_chassis.png'),
('Muffled Blade', 9, 'Very Rare', 'assets/img/killer/addon/muffled_blade.png'),

-- The Nightmare (Freddy Krueger, ID: 10)
('Wool Shirt', 10, 'Common', 'assets/img/killer/addon/wool_shirt.png'),
('Sheep Block', 10, 'Uncommon', 'assets/img/killer/addon/sheep_block.png'),
('Kid’s Drawing', 10, 'Common', 'assets/img/killer/addon/kids_drawing.png'),
('Garden Rake', 10, 'Uncommon', 'assets/img/killer/addon/garden_rake.png'),
('Prototype Claws', 10, 'Rare', 'assets/img/killer/addon/prototype_claws.png'),
('Outdoor Rope', 10, 'Uncommon', 'assets/img/killer/addon/outdoor_rope.png'),
('Nancy’s Sketch', 10, 'Uncommon', 'assets/img/killer/addon/nancys_sketch.png'),
('Green Dress', 10, 'Uncommon', 'assets/img/killer/addon/green_dress.png'),
('Unicorn Block', 10, 'Rare', 'assets/img/killer/addon/unicorn_block.png'),
('Nancy’s Masterpiece', 10, 'Rare', 'assets/img/killer/addon/nancys_masterpiece.png'),
('Jump Rope', 10, 'Rare', 'assets/img/killer/addon/jump_rope.png'),
('Blue Dress', 10, 'Rare', 'assets/img/killer/addon/blue_dress.png'),
('Pill Bottle', 10, 'Very Rare', 'assets/img/killer/addon/pill_bottle.png'),
('Swing Chains', 10, 'Very Rare', 'assets/img/killer/addon/swing_chains.png'),
('Class Photo', 10, 'Very Rare', 'assets/img/killer/addon/class_photo.png'),
('Z Block', 10, 'Very Rare', 'assets/img/killer/addon/z_block.png'),
('Red Paint Brush', 10, 'Ultra Rare', 'assets/img/killer/addon/red_paint_brush.png'),
('Black Box', 10, 'Ultra Rare', 'assets/img/killer/addon/black_box.png'),
('Cat Block', 10, 'Rare', 'assets/img/killer/addon/cat_block.png'),
('Paint Thinner', 10, 'Uncommon', 'assets/img/killer/addon/paint_thinner.png'),

-- The Pig (Amanda Young, ID: 11)
('Workshop Grease', 11, 'Common', 'assets/img/killer/addon/workshop_grease.png'),
('Combat Straps', 11, 'Common', 'assets/img/killer/addon/combat_straps.png'),
('Shattered Syringe', 11, 'Common', 'assets/img/killer/addon/shattered_syringe.png'),
('John’s Medical File', 11, 'Common', 'assets/img/killer/addon/johns_medical_file.png'),
('Razor Wires', 11, 'Uncommon', 'assets/img/killer/addon/razor_wires.png'),
('Last Will', 11, 'Uncommon', 'assets/img/killer/addon/last_will.png'),
('Face Mask', 11, 'Uncommon', 'assets/img/killer/addon/face_mask.png'),
('Slow-Release Toxin', 11, 'Uncommon', 'assets/img/killer/addon/slow_release_toxin.png'),
('Rusty Attachments', 11, 'Rare', 'assets/img/killer/addon/rusty_attachments.png'),
('Jigsaw’s Sketch', 11, 'Rare', 'assets/img/killer/addon/jigsaws_sketch.png'),
('Interlocking Razor', 11, 'Rare', 'assets/img/killer/addon/interlocking_razor.png'),
('Bag of Gears', 11, 'Rare', 'assets/img/killer/addon/bag_of_gears.png'),
('Tampered Timer', 11, 'Very Rare', 'assets/img/killer/addon/tampered_timer.png'),
('Jigsaw’s Annotated Plan', 11, 'Very Rare', 'assets/img/killer/addon/jigsaws_annotated_plan.png'),
('Crate of Gears', 11, 'Very Rare', 'assets/img/killer/addon/crate_of_gears.png'),
('Amanda’s Secret', 11, 'Very Rare', 'assets/img/killer/addon/amandas_secret.png'),
('Rules Set No.2', 11, 'Ultra Rare', 'assets/img/killer/addon/rules_set_no2.png'),
('Amanda’s Letter', 11, 'Ultra Rare', 'assets/img/killer/addon/amandas_letter.png'),
('Video Tape', 11, 'Uncommon', 'assets/img/killer/addon/video_tape.png'),
('Utility Blades', 11, 'Rare', 'assets/img/killer/addon/utility_blades.png'),

-- The Clown (Jeffrey Hawk, ID: 12)
('Smelly Inner Soles', 12, 'Common', 'assets/img/killer/addon/smelly_inner_soles.png'),
('Robin Feather', 12, 'Common', 'assets/img/killer/addon/robin_feather.png'),
('Fingerless Parade Gloves', 12, 'Common', 'assets/img/killer/addon/fingerless_parade_gloves.png'),
('Kerosene Can', 12, 'Uncommon', 'assets/img/killer/addon/kerosene_can.png'),
('Vodka Bottle', 12, 'Uncommon', 'assets/img/killer/addon/vodka_bottle.png'),
('Sulphuric Acid Vial', 12, 'Uncommon', 'assets/img/killer/addon/sulphuric_acid_vial.png'),
('Starling Feather', 12, 'Uncommon', 'assets/img/killer/addon/starling_feather.png'),
('Solvent Jug', 12, 'Uncommon', 'assets/img/killer/addon/solvent_jug.png'),
('Thick Cork Stopper', 12, 'Rare', 'assets/img/killer/addon/thick_cork_stopper.png'),
('Sticky Soda Bottle', 12, 'Rare', 'assets/img/killer/addon/sticky_soda_bottle.png'),
('Cheap Gin Bottle', 12, 'Rare', 'assets/img/killer/addon/cheap_gin_bottle.png'),
('Smoking Pipe', 12, 'Rare', 'assets/img/killer/addon/smoking_pipe.png'),
('Party Bottle', 12, 'Very Rare', 'assets/img/killer/addon/party_bottle.png'),
('Ether 15 Vol%', 12, 'Very Rare', 'assets/img/killer/addon/ether_15_vol.png'),
('Cigar Box', 12, 'Very Rare', 'assets/img/killer/addon/cigar_box.png'),
('Garish Make-up Kit', 12, 'Very Rare', 'assets/img/killer/addon/garish_makeup_kit.png'),
('Redhead’s Pinky Finger', 12, 'Ultra Rare', 'assets/img/killer/addon/redheads_pinky_finger.png'),
('Iridescent Bottle', 12, 'Ultra Rare', 'assets/img/killer/addon/iridescent_bottle.png'),
('Tattoo’s Middle Finger', 12, 'Rare', 'assets/img/killer/addon/tattoos_middle_finger.png'),
('Flask of Bleach', 12, 'Uncommon', 'assets/img/killer/addon/flask_of_bleach.png'),

-- The Spirit (Rin Yamaoka, ID: 13)
('Zori', 13, 'Common', 'assets/img/killer/addon/zori.png'),
('Shiawase Amulet', 13, 'Common', 'assets/img/killer/addon/shiawase_amulet.png'),
('Origami Crane', 13, 'Common', 'assets/img/killer/addon/origami_crane.png'),
('Gifted Bamboo Comb', 13, 'Common', 'assets/img/killer/addon/gifted_bamboo_comb.png'),
('White Hair Ribbon', 13, 'Uncommon', 'assets/img/killer/addon/white_hair_ribbon.png'),
('Rusted Katana', 13, 'Uncommon', 'assets/img/killer/addon/rusted_katana.png'),
('Prayer Beads Bracelet', 13, 'Uncommon', 'assets/img/killer/addon/prayer_beads_bracelet.png'),
('Juniper Bonsai', 13, 'Uncommon', 'assets/img/killer/addon/juniper_bonsai.png'),
('Rin’s Broken Watch', 13, 'Rare', 'assets/img/killer/addon/rins_broken_watch.png'),
('Muddy Sports Day Cap', 13, 'Rare', 'assets/img/killer/addon/muddy_sports_day_cap.png'),
('Kaiun Talisman', 13, 'Rare', 'assets/img/killer/addon/kaiun_talisman.png'),
('Katana Tsuba', 13, 'Rare', 'assets/img/killer/addon/katana_tsuba.png'),
('Yakuyoke Amulet', 13, 'Very Rare', 'assets/img/killer/addon/yakuyoke_amulet.png'),
('Wakizashi Saya', 13, 'Very Rare', 'assets/img/killer/addon/wakizashi_saya.png'),
('Uchiwa', 13, 'Very Rare', 'assets/img/killer/addon/uchiwa.png'),
('Senko Hanabi', 13, 'Very Rare', 'assets/img/killer/addon/senko_hanabi.png'),
('Mother-Daughter Ring', 13, 'Ultra Rare', 'assets/img/killer/addon/mother_daughter_ring.png'),
('Iridescent Talisman', 13, 'Ultra Rare', 'assets/img/killer/addon/iridescent_talisman.png'),
('Dried Cherry Blossom', 13, 'Rare', 'assets/img/killer/addon/dried_cherry_blossom.png'),
('Bloody Hair Brooch', 13, 'Uncommon', 'assets/img/killer/addon/bloody_hair_brooch.png'),

-- The Legion (Frank, Julie, Susie, Joey, ID: 14)
('Smiley Face Pin', 14, 'Common', 'assets/img/killer/addon/smiley_face_pin.png'),
('Scratched Ruler', 14, 'Common', 'assets/img/killer/addon/scratched_ruler.png'),
('Mischief List', 14, 'Common', 'assets/img/killer/addon/mischief_list.png'),
('Friendship Bracelet', 14, 'Common', 'assets/img/killer/addon/friendship_bracelet.png'),
('Never-Sleep Pills', 14, 'Uncommon', 'assets/img/killer/addon/never_sleep_pills.png'),
('Mural Sketch', 14, 'Uncommon', 'assets/img/killer/addon/mural_sketch.png'),
('Julie’s Mix Tape', 14, 'Uncommon', 'assets/img/killer/addon/julies_mix_tape.png'),
('Etched Ruler', 14, 'Uncommon', 'assets/img/killer/addon/etched_ruler.png'),
('Defaced Smiley Pin', 14, 'Uncommon', 'assets/img/killer/addon/defaced_smiley_pin.png'),
('The Legion Pin', 14, 'Rare', 'assets/img/killer/addon/the_legion_pin.png'),
('Susie’s Mix Tape', 14, 'Rare', 'assets/img/killer/addon/susies_mix_tape.png'),
('Stolen Sketch Book', 14, 'Rare', 'assets/img/killer/addon/stolen_sketch_book.png'),
('Nasty Blade', 14, 'Rare', 'assets/img/killer/addon/nasty_blade.png'),
('Joey’s Mix Tape', 14, 'Rare', 'assets/img/killer/addon/joeys_mix_tape.png'),
('Stab Wounds Study', 14, 'Very Rare', 'assets/img/killer/addon/stab_wounds_study.png'),
('Frank’s Mix Tape', 14, 'Very Rare', 'assets/img/killer/addon/franks_mix_tape.png'),
('Filthy Blade', 14, 'Very Rare', 'assets/img/killer/addon/filthy_blade.png'),
('Cold Dirt', 14, 'Very Rare', 'assets/img/killer/addon/cold_dirt.png'),
('Iridescent Button', 14, 'Ultra Rare', 'assets/img/killer/addon/iridescent_button.png'),
('Fuming Mix Tape', 14, 'Ultra Rare', 'assets/img/killer/addon/fuming_mix_tape.png'),

-- The Plague (Adiris, ID: 15)
('Prayer Tablet Fragment', 15, 'Common', 'assets/img/killer/addon/prayer_tablet_fragment.png'),
('Olibanum Incense', 15, 'Common', 'assets/img/killer/addon/olibanum_incense.png'),
('Limestone Seal', 15, 'Common', 'assets/img/killer/addon/limestone_seal.png'),
('Healing Salve', 15, 'Common', 'assets/img/killer/addon/healing_salve.png'),
('Prophylactic Amulet', 15, 'Uncommon', 'assets/img/killer/addon/prophylactic_amulet.png'),
('Potent Tincture', 15, 'Uncommon', 'assets/img/killer/addon/potent_tincture.png'),
('Emetic Potion', 15, 'Uncommon', 'assets/img/killer/addon/emetic_potion.png'),
('Blessed Apple', 15, 'Uncommon', 'assets/img/killer/addon/blessed_apple.png'),
('Ashen Apple', 15, 'Uncommon', 'assets/img/killer/addon/ashen_apple.png'),
('Incensed Ointment', 15, 'Rare', 'assets/img/killer/addon/incensed_ointment.png'),
('Exorcism Amulet', 15, 'Rare', 'assets/img/killer/addon/exorcism_amulet.png'),
('Devotee’s Amulet', 15, 'Rare', 'assets/img/killer/addon/devotees_amulet.png'),
('Vile Emetic', 15, 'Rare', 'assets/img/killer/addon/vile_emetic.png'),
('Severed Toe', 15, 'Rare', 'assets/img/killer/addon/severed_toe.png'),
('Worship Tablet', 15, 'Very Rare', 'assets/img/killer/addon/worship_tablet.png'),
('Infectious Fright', 15, 'Very Rare', 'assets/img/killer/addon/infectious_fright.png'),
('Effigy Remains', 15, 'Very Rare', 'assets/img/killer/addon/effigy_remains.png'),
('Black Incense', 15, 'Very Rare', 'assets/img/killer/addon/black_incense.png'),
('Iridescent Seal', 15, 'Ultra Rare', 'assets/img/killer/addon/iridescent_seal_plague.png'),
('Vile Purge', 15, 'Ultra Rare', 'assets/img/killer/addon/vile_purge.png'),

-- The Ghost Face (Danny Johnson, ID: 16)
('Philly', 16, 'Common', 'assets/img/killer/addon/philly.png'),
('Walleye’s Matchbook', 16, 'Common', 'assets/img/killer/addon/walleyes_matchbook.png'),
('Headlines Cut-outs', 16, 'Common', 'assets/img/killer/addon/headlines_cutouts.png'),
('Cheap Cologne', 16, 'Common', 'assets/img/killer/addon/cheap_cologne.png'),
('Telephoto Lens', 16, 'Uncommon', 'assets/img/killer/addon/telephoto_lens.png'),
('Reusable Cinch Straps', 16, 'Uncommon', 'assets/img/killer/addon/reusable_cinch_straps.png'),
('Olsen’s Journal', 16, 'Uncommon', 'assets/img/killer/addon/olsens_journal.png'),
('Olsen’s Address Book', 16, 'Uncommon', 'assets/img/killer/addon/olsens_address_book.png'),
('Marked Map', 16, 'Uncommon', 'assets/img/killer/addon/marked_map.png'),
('Olsen’s Wallet', 16, 'Rare', 'assets/img/killer/addon/olsens_wallet.png'),
('Leather Knife Sheath', 16, 'Rare', 'assets/img/killer/addon/leather_knife_sheath.png'),
('Lasting Perfume', 16, 'Rare', 'assets/img/killer/addon/lasting_perfume.png'),
('Knife Belt Clip', 16, 'Rare', 'assets/img/killer/addon/knife_belt_clip.png'),
('Chewed Pen', 16, 'Rare', 'assets/img/killer/addon/chewed_pen.png'),
('Victim’s Detailed Routine', 16, 'Very Rare', 'assets/img/killer/addon/victims_detailed_routine.png'),
('Night Vision Monocular', 16, 'Very Rare', 'assets/img/killer/addon/night_vision_monocular.png'),
('Drop-Leg Knife Sheath', 16, 'Very Rare', 'assets/img/killer/addon/drop_leg_knife_sheath.png'),
('Driver’s License', 16, 'Very Rare', 'assets/img/killer/addon/drivers_license.png'),
('Iridescent Pendant', 16, 'Ultra Rare', 'assets/img/killer/addon/iridescent_pendant_ghostface.png'),
('Ghost Face Caught on Tape', 16, 'Ultra Rare', 'assets/img/killer/addon/ghost_face_caught_on_tape.png'),

-- The Demogorgon (ID: 17)
('Rotten Pumpkin', 17, 'Common', 'assets/img/killer/addon/rotten_pumpkin.png'),
('Black Heart', 17, 'Common', 'assets/img/killer/addon/black_heart.png'),
('Rat Liver', 17, 'Common', 'assets/img/killer/addon/rat_liver.png'),
('Rat Tail', 17, 'Common', 'assets/img/killer/addon/rat_tail.png'),
('Rotten Green Tripe', 17, 'Uncommon', 'assets/img/killer/addon/rotten_green_tripe.png'),
('Mew’s Guts', 17, 'Uncommon', 'assets/img/killer/addon/mews_guts.png'),
('Barb’s Glasses', 17, 'Uncommon', 'assets/img/killer/addon/barbs_glasses.png'),
('Viscous Webbing', 17, 'Uncommon', 'assets/img/killer/addon/viscous_webbing.png'),
('Vermilion Webcap', 17, 'Uncommon', 'assets/img/killer/addon/vermilion_webcap.png'),
('Upside Down Resin', 17, 'Rare', 'assets/img/killer/addon/upside_down_resin.png'),
('Unknown Egg', 17, 'Rare', 'assets/img/killer/addon/unknown_egg.png'),
('Deer Lung', 17, 'Rare', 'assets/img/killer/addon/deer_lung.png'),
('Elevens Soda', 17, 'Rare', 'assets/img/killer/addon/elevens_soda.png'),
('Brass Case Lighter', 17, 'Rare', 'assets/img/killer/addon/brass_case_lighter.png'),
('Violet Waxcap', 17, 'Very Rare', 'assets/img/killer/addon/violet_waxcap.png'),
('Lifeguard Whistle', 17, 'Very Rare', 'assets/img/killer/addon/lifeguard_whistle.png'),
('Leprose Lichen', 17, 'Very Rare', 'assets/img/killer/addon/leprose_lichen.png'),
('Red Moss', 17, 'Very Rare', 'assets/img/killer/addon/red_moss.png'),
('Iridescent Necklace', 17, 'Ultra Rare', 'assets/img/killer/addon/iridescent_necklace.png'),
('Demogorgon’s Seal', 17, 'Ultra Rare', 'assets/img/killer/addon/demogorgons_seal.png'),

-- The Oni (Kazan Yamaoka, ID: 18)
('Wooden Oni Mask', 18, 'Common', 'assets/img/killer/addon/wooden_oni_mask.png'),
('Shattered Wakizashi', 18, 'Common', 'assets/img/killer/addon/shattered_wakizashi.png'),
('Yamaoka’s Crest', 18, 'Common', 'assets/img/killer/addon/yamaokas_crest.png'),
('Blackened Toenail', 18, 'Common', 'assets/img/killer/addon/blackened_toenail.png'),
('Polished Maedate', 18, 'Uncommon', 'assets/img/killer/addon/polished_maedate.png'),
('Ink Lion', 18, 'Uncommon', 'assets/img/killer/addon/ink_lion.png'),
('Chipped Saihai', 18, 'Uncommon', 'assets/img/killer/addon/chipped_saihai.png'),
('Child’s Wooden Sword', 18, 'Uncommon', 'assets/img/killer/addon/childs_wooden_sword.png'),
('Bloody Sash', 18, 'Uncommon', 'assets/img/killer/addon/bloody_sash.png'),
('Yamaoka’s Tuning Blade', 18, 'Rare', 'assets/img/killer/addon/yamaokas_tuning_blade.png'),
('Scalped Topknot', 18, 'Rare', 'assets/img/killer/addon/scalped_topknot.png'),
('Kanai-Anzen Talisman', 18, 'Rare', 'assets/img/killer/addon/kanai_anzen_talisman.png'),
('Cracked Sakazuki', 18, 'Rare', 'assets/img/killer/addon/cracked_sakazuki.png'),
('Akito’s Crutch', 18, 'Rare', 'assets/img/killer/addon/akitos_crutch.png'),
('Splintered Hull', 18, 'Very Rare', 'assets/img/killer/addon/splintered_hull.png'),
('Renjiro’s Bloody Glove', 18, 'Very Rare', 'assets/img/killer/addon/renjiros_bloody_glove.png'),
('Lion Fang', 18, 'Very Rare', 'assets/img/killer/addon/lion_fang.png'),
('Iron Hammer', 18, 'Very Rare', 'assets/img/killer/addon/iron_hammer.png'),
('Iridescent Family Crest', 18, 'Ultra Rare', 'assets/img/killer/addon/iridescent_family_crest.png'),
('Tear-Soaked Tenugui', 18, 'Ultra Rare', 'assets/img/killer/addon/tear_soaked_tenugui.png'),

-- The Deathslinger (Caleb Quinn, ID: 19)
('Spit Polish Rag', 19, 'Common', 'assets/img/killer/addon/spit_polish_rag.png'),
('Snake Oil', 19, 'Common', 'assets/img/killer/addon/snake_oil.png'),
('Rickety Chain', 19, 'Common', 'assets/img/killer/addon/rickety_chain.png'),
('Modified Ammo Belt', 19, 'Common', 'assets/img/killer/addon/modified_ammo_belt.png'),
('Rusted Spike', 19, 'Uncommon', 'assets/img/killer/addon/rusted_spike.png'),
('Poison Oak Leaves', 19, 'Uncommon', 'assets/img/killer/addon/poison_oak_leaves.png'),
('Marshal’s Badge', 19, 'Uncommon', 'assets/img/killer/addon/marshals_badge.png'),
('Jaw Smasher', 19, 'Uncommon', 'assets/img/killer/addon/jaw_smasher.png'),
('Chewing Tobacco', 19, 'Uncommon', 'assets/img/killer/addon/chewing_tobacco.png'),
('Warden’s Keys', 19, 'Rare', 'assets/img/killer/addon/wardens_keys.png'),
('Wanted Poster', 19, 'Rare', 'assets/img/killer/addon/wanted_poster.png'),
('Tin Oil Can', 19, 'Rare', 'assets/img/killer/addon/tin_oil_can.png'),
('Honey Locust Thorn', 19, 'Rare', 'assets/img/killer/addon/honey_locust_thorn.png'),
('Bayshore’s Gold Tooth', 19, 'Rare', 'assets/img/killer/addon/bayshores_gold_tooth.png'),
('Prison Chain', 19, 'Very Rare', 'assets/img/killer/addon/prison_chain.png'),
('Gold Creek Whiskey', 19, 'Very Rare', 'assets/img/killer/addon/gold_creek_whiskey.png'),
('Bayshore’s Cigar', 19, 'Very Rare', 'assets/img/killer/addon/bayshores_cigar.png'),
('Barbed Wire', 19, 'Very Rare', 'assets/img/killer/addon/barbed_wire.png'),
('Iridescent Coin', 19, 'Ultra Rare', 'assets/img/killer/addon/iridescent_coin.png'),
('Hellshire Iron', 19, 'Ultra Rare', 'assets/img/killer/addon/hellshire_iron.png'),

-- The Executioner (Pyramid Head, ID: 20)
('Copper Ring', 20, 'Common', 'assets/img/killer/addon/copper_ring.png'),
('Dead Butterfly', 20, 'Common', 'assets/img/killer/addon/dead_butterfly.png'),
('Spearhead', 20, 'Common', 'assets/img/killer/addon/spearhead.png'),
('Cinderella Music Box', 20, 'Common', 'assets/img/killer/addon/cinderella_music_box.png'),
('Wax Doll', 20, 'Uncommon', 'assets/img/killer/addon/wax_doll.png'),
('Mannequin Foot', 20, 'Uncommon', 'assets/img/killer/addon/mannequin_foot.png'),
('Burning Man Painting', 20, 'Uncommon', 'assets/img/killer/addon/burning_man_painting.png'),
('Black Strap', 20, 'Uncommon', 'assets/img/killer/addon/black_strap.png'),
('Lead Ring', 20, 'Rare', 'assets/img/killer/addon/lead_ring.png'),
('Misty Day Remains', 20, 'Rare', 'assets/img/killer/addon/misty_day_remains.png'),
('Obsidian Goblet', 20, 'Rare', 'assets/img/killer/addon/obsidian_goblet.png'),
('Rust-Colored Egg', 20, 'Rare', 'assets/img/killer/addon/rust_colored_egg.png'),
('Scarlet Egg', 20, 'Rare', 'assets/img/killer/addon/scarlet_egg.png'),
('Valtiel Sect Photograph', 20, 'Very Rare', 'assets/img/killer/addon/valtiel_sect_photograph.png'),
('Flaming Oath', 20, 'Very Rare', 'assets/img/killer/addon/flaming_oath.png'),
('Lost Memories Book', 20, 'Very Rare', 'assets/img/killer/addon/lost_memories_book.png'),
('Crimson Ceremony Book', 20, 'Very Rare', 'assets/img/killer/addon/crimson_ceremony_book.png'),
('Iridescent Seal of Metatron', 20, 'Ultra Rare', 'assets/img/killer/addon/iridescent_seal_of_metatron.png'),
('Leviathan’s Jawbone', 20, 'Ultra Rare', 'assets/img/killer/addon/leviathans_jawbone.png'),
('Tablet of the Oppressor', 20, 'Uncommon', 'assets/img/killer/addon/tablet_of_the_oppressor.png'),

-- The Blight (Talbot Grimes, ID: 21)
('Placebo Tablet', 21, 'Common', 'assets/img/killer/addon/placebo_tablet.png'),
('Foxglove', 21, 'Common', 'assets/img/killer/addon/foxglove.png'),
('Compound Seven', 21, 'Common', 'assets/img/killer/addon/compound_seven.png'),
('Chipped Monocle', 21, 'Common', 'assets/img/killer/addon/chipped_monocle.png'),
('Shredded Notes', 21, 'Uncommon', 'assets/img/killer/addon/shredded_notes.png'),
('Pustula Dust', 21, 'Uncommon', 'assets/img/killer/addon/pustula_dust.png'),
('Plague Bile', 21, 'Uncommon', 'assets/img/killer/addon/plague_bile.png'),
('Canker Thorn', 21, 'Uncommon', 'assets/img/killer/addon/canker_thorn.png'),
('Blighted Rat', 21, 'Uncommon', 'assets/img/killer/addon/blighted_rat.png'),
('Vigo’s Journal', 21, 'Rare', 'assets/img/killer/addon/vigos_journal.png'),
('Umbra Salts', 21, 'Rare', 'assets/img/killer/addon/umbra_salts.png'),
('Soul Chemical', 21, 'Rare', 'assets/img/killer/addon/soul_chemical.png'),
('Rose Tonic', 21, 'Rare', 'assets/img/killer/addon/rose_tonic.png'),
('Compound Twenty-One', 21, 'Rare', 'assets/img/killer/addon/compound_twenty_one.png'),
('Summoning Stone', 21, 'Very Rare', 'assets/img/killer/addon/summoning_stone.png'),
('Blighted Crow', 21, 'Very Rare', 'assets/img/killer/addon/blighted_crow.png'),
('Adrenaline Vial', 21, 'Very Rare', 'assets/img/killer/addon/adrenaline_vial.png'),
('Alchemist’s Ring', 21, 'Very Rare', 'assets/img/killer/addon/alchemists_ring.png'),
('Iridescent Blight Tag', 21, 'Ultra Rare', 'assets/img/killer/addon/iridescent_blight_tag.png'),
('Compound Thirty-Three', 21, 'Ultra Rare', 'assets/img/killer/addon/compound_thirty_three.png'),

-- The Twins (Charlotte & Victor Deshayes, ID: 22)
('Toy Sword', 22, 'Common', 'assets/img/killer/addon/toy_sword.png'),
('Tiny Fingernail', 22, 'Common', 'assets/img/killer/addon/tiny_fingernail.png'),
('Madeleine’s Glove', 22, 'Common', 'assets/img/killer/addon/madeleines_glove.png'),
('Cat Figurine', 22, 'Common', 'assets/img/killer/addon/cat_figurine.png'),
('Sour Candy', 22, 'Uncommon', 'assets/img/killer/addon/sour_candy.png'),
('Sewer Sludge', 22, 'Uncommon', 'assets/img/killer/addon/sewer_sludge.png'),
('Rusted Needle', 22, 'Uncommon', 'assets/img/killer/addon/rusted_needle.png'),
('Cat’s Eye', 22, 'Uncommon', 'assets/img/killer/addon/cats_eye.png'),
('Ceremonial Candelabrum', 22, 'Uncommon', 'assets/img/killer/addon/ceremonial_candelabrum.png'),
('Weighty Rattle', 22, 'Rare', 'assets/img/killer/addon/weighty_rattle.png'),
('Stale Biscuit', 22, 'Rare', 'assets/img/killer/addon/stale_biscuit.png'),
('Sewing Kit', 22, 'Rare', 'assets/img/killer/addon/sewing_kit.png'),
('Forest Stew', 22, 'Rare', 'assets/img/killer/addon/forest_stew.png'),
('Drop of Perfume', 22, 'Rare', 'assets/img/killer/addon/drop_of_perfume.png'),
('Victor’s Soldier', 22, 'Very Rare', 'assets/img/killer/addon/victors_soldier.png'),
('Spinning Top', 22, 'Very Rare', 'assets/img/killer/addon/spinning_top.png'),
('Silencing Cloth', 22, 'Very Rare', 'assets/img/killer/addon/silencing_cloth.png'),
('Iridescent Pendant', 22, 'Ultra Rare', 'assets/img/killer/addon/iridescent_pendant_twins.png'),
('Madeleine’s Scarf', 22, 'Ultra Rare', 'assets/img/killer/addon/madeleines_scarf.png'),
('Baby Teeth', 22, 'Uncommon', 'assets/img/killer/addon/baby_teeth.png'),

-- The Trickster (Ji-Woon Hak, ID: 23)
('Melodious Murder', 23, 'Common', 'assets/img/killer/addon/melodious_murder.png'),
('Fizz-Spin Soda', 23, 'Common', 'assets/img/killer/addon/fizz_spin_soda.png'),
('Caged Heart Shoes', 23, 'Common', 'assets/img/killer/addon/caged_heart_shoes.png'),
('Bloody Boa', 23, 'Common', 'assets/img/killer/addon/bloody_boa.png'),
('Trick Pouch', 23, 'Uncommon', 'assets/img/killer/addon/trick_pouch.png'),
('Sticky Soda Bottle', 23, 'Uncommon', 'assets/img/killer/addon/sticky_soda_bottle.png'),
('Starstruck Champagne', 23, 'Uncommon', 'assets/img/killer/addon/starstruck_champagne.png'),
('Ji-Woon’s Autograph', 23, 'Uncommon', 'assets/img/killer/addon/ji_woons_autograph.png'),
('Vodka Bottle', 23, 'Uncommon', 'assets/img/killer/addon/vodka_bottle_trickster.png'),
('Killing Part Chords', 23, 'Rare', 'assets/img/killer/addon/killing_part_chords.png'),
('Inferno Wires', 23, 'Rare', 'assets/img/killer/addon/inferno_wires.png'),
('Tequila Moonrock', 23, 'Rare', 'assets/img/killer/addon/tequila_moonrock.png'),
('On Target Single', 23, 'Rare', 'assets/img/killer/addon/on_target_single.png'),
('Lucky Blade', 23, 'Rare', 'assets/img/killer/addon/lucky_blade.png'),
('Waiting For You Watch', 23, 'Very Rare', 'assets/img/killer/addon/waiting_for_you_watch.png'),
('Memento Blades', 23, 'Very Rare', 'assets/img/killer/addon/memento_blades.png'),
('Death Throes Compilation', 23, 'Very Rare', 'assets/img/killer/addon/death_throes_compilation.png'),
('Diamond Cufflinks', 23, 'Very Rare', 'assets/img/killer/addon/diamond_cufflinks.png'),
('Iridescent Photocard', 23, 'Ultra Rare', 'assets/img/killer/addon/iridescent_photocard.png'),
('Cut Throat', 23, 'Ultra Rare', 'assets/img/killer/addon/cut_throat.png'),

-- The Nemesis (Nemesis-T Type, ID: 24)
('Zombie Heart', 24, 'Common', 'assets/img/killer/addon/zombie_heart.png'),
('Viscera Sample', 24, 'Common', 'assets/img/killer/addon/viscera_sample.png'),
('T-Virus Sample', 24, 'Common', 'assets/img/killer/addon/t_virus_sample.png'),
('S.T.A.R.S. Field Manual', 24, 'Common', 'assets/img/killer/addon/stars_field_manual.png'),
('Tyrant Gore', 24, 'Uncommon', 'assets/img/killer/addon/tyrant_gore.png'),
('Serotonin Injector', 24, 'Uncommon', 'assets/img/killer/addon/serotonin_injector.png'),
('NE-a Parasite', 24, 'Uncommon', 'assets/img/killer/addon/ne_a_parasite.png'),
('Jill’s Sandwich', 24, 'Uncommon', 'assets/img/killer/addon/jills_sandwich.png'),
('Depleted Ink Ribbon', 24, 'Uncommon', 'assets/img/killer/addon/depleted_ink_ribbon.png'),
('Umbrella Medallion', 24, 'Rare', 'assets/img/killer/addon/umbrella_medallion.png'),
('Shattered S.T.A.R.S. Badge', 24, 'Rare', 'assets/img/killer/addon/shattered_stars_badge.png'),
('Licker Tongue', 24, 'Rare', 'assets/img/killer/addon/licker_tongue.png'),
('Broken Recovery Coin', 24, 'Rare', 'assets/img/killer/addon/broken_recovery_coin.png'),
('Admin Wristband', 24, 'Rare', 'assets/img/killer/addon/admin_wristband.png'),
('T-Virus Vaccine', 24, 'Very Rare', 'assets/img/killer/addon/t_virus_vaccine.png'),
('Nemesis Arm', 24, 'Very Rare', 'assets/img/killer/addon/nemesis_arm.png'),
('Mikhail’s Eye', 24, 'Very Rare', 'assets/img/killer/addon/mikhails_eye.png'),
('Damaged Syringe', 24, 'Very Rare', 'assets/img/killer/addon/damaged_syringe.png'),
('Iridescent Umbrella Badge', 24, 'Ultra Rare', 'assets/img/killer/addon/iridescent_umbrella_badge.png'),
('Adrenaline Injector', 24, 'Ultra Rare', 'assets/img/killer/addon/adrenaline_injector.png'),

-- The Cenobite (Pinhead, ID: 25)
('Wriggling Maggot', 25, 'Common', 'assets/img/killer/addon/wriggling_maggot.png'),
('Spoiled Rations', 25, 'Common', 'assets/img/killer/addon/spoiled_rations.png'),
('Skewered Rat', 25, 'Common', 'assets/img/killer/addon/skewered_rat.png'),
('Bent Nail', 25, 'Common', 'assets/img/killer/addon/bent_nail.png'),
('Slick Pin', 25, 'Uncommon', 'assets/img/killer/addon/slick_pin.png'),
('Leather Strip', 25, 'Uncommon', 'assets/img/killer/addon/leather_strip.png'),
('Frank’s Heart', 25, 'Uncommon', 'assets/img/killer/addon/franks_heart.png'),
('Burning Candle', 25, 'Uncommon', 'assets/img/killer/addon/burning_candle.png'),
('Lively Crickets', 25, 'Uncommon', 'assets/img/killer/addon/lively_crickets.png'),
('Torture Pillar', 25, 'Rare', 'assets/img/killer/addon/torture_pillar.png'),
('Slice of Frank', 25, 'Rare', 'assets/img/killer/addon/slice_of_frank.png'),
('Larry’s Remains', 25, 'Rare', 'assets/img/killer/addon/larrys_remains.png'),
('Grease-Smeared Glasses', 25, 'Rare', 'assets/img/killer/addon/grease_smeared_glasses.png'),
('Chatterer’s Tooth', 25, 'Rare', 'assets/img/killer/addon/chatterers_tooth.png'),
('Original Pain', 25, 'Very Rare', 'assets/img/killer/addon/original_pain.png'),
('Liquified Gore', 25, 'Very Rare', 'assets/img/killer/addon/liquified_gore.png'),
('Impalable Hook', 25, 'Very Rare', 'assets/img/killer/addon/impalable_hook.png'),
('Engineer’s Fang', 25, 'Very Rare', 'assets/img/killer/addon/engineers_fang.png'),
('Iridescent Lament Configuration', 25, 'Ultra Rare', 'assets/img/killer/addon/iridescent_lament_configuration.png'),
('Cenobite’s Pin', 25, 'Ultra Rare', 'assets/img/killer/addon/cenobites_pin.png'),

-- The Artist (Carmina Mora, ID: 26)
('Thick Tar', 26, 'Common', 'assets/img/killer/addon/thick_tar.png'),
('Silver Bell', 26, 'Common', 'assets/img/killer/addon/silver_bell.png'),
('Oil Paints', 26, 'Common', 'assets/img/killer/addon/oil_paints.png'),
('Choclo Corn', 26, 'Common', 'assets/img/killer/addon/choclo_corn.png'),
('Untamed Donkey', 26, 'Uncommon', 'assets/img/killer/addon/untamed_donkey.png'),
('Severed Tongue', 26, 'Uncommon', 'assets/img/killer/addon/severed_tongue.png'),
('Frayed Cotton Rag', 26, 'Uncommon', 'assets/img/killer/addon/frayed_cotton_rag.png'),
('Charcoal Stick', 26, 'Uncommon', 'assets/img/killer/addon/charcoal_stick.png'),
('Automatic Drawing', 26, 'Uncommon', 'assets/img/killer/addon/automatic_drawing.png'),
('Velvet Fabric', 26, 'Rare', 'assets/img/killer/addon/velvet_fabric.png'),
('Vibrant Obituary', 26, 'Rare', 'assets/img/killer/addon/vibrant_obituary.png'),
('Owl Feather', 26, 'Rare', 'assets/img/killer/addon/owl_feather.png'),
('Matias’ Baby Shoes', 26, 'Rare', 'assets/img/killer/addon/matias_baby_shoes.png'),
('Ink Egg', 26, 'Rare', 'assets/img/killer/addon/ink_egg.png'),
('Severed Hands', 26, 'Very Rare', 'assets/img/killer/addon/severed_hands.png'),
('Garden of Rot', 26, 'Very Rare', 'assets/img/killer/addon/garden_of_rot.png'),
('Darkest Ink', 26, 'Very Rare', 'assets/img/killer/addon/darkest_ink.png'),
('Crow’s Eye', 26, 'Very Rare', 'assets/img/killer/addon/crows_eye.png'),
('Iridescent Feather', 26, 'Ultra Rare', 'assets/img/killer/addon/iridescent_feather.png'),
('Grim Pilgrimage', 26, 'Ultra Rare', 'assets/img/killer/addon/grim_pilgrimage.png'),

-- The Onryō (Sadako Yamamura, ID: 27)
('Videotape Copy', 27, 'Common', 'assets/img/killer/addon/videotape_copy.png'),
('Tape Editing Deck', 27, 'Common', 'assets/img/killer/addon/tape_editing_deck.png'),
('Reiko’s Watch', 27, 'Common', 'assets/img/killer/addon/reikos_watch.png'),
('Old Newspaper', 27, 'Common', 'assets/img/killer/addon/old_newspaper.png'),
('Yoichi’s Fishing Net', 27, 'Uncommon', 'assets/img/killer/addon/yoichis_fishing_net.png'),
('Sea-Soaked Cloth', 27, 'Uncommon', 'assets/img/killer/addon/sea_soaked_cloth.png'),
('Clump of Hair', 27, 'Uncommon', 'assets/img/killer/addon/clump_of_hair.png'),
('Cabin Sign', 27, 'Uncommon', 'assets/img/killer/addon/cabin_sign.png'),
('Well Stone', 27, 'Uncommon', 'assets/img/killer/addon/well_stone.png'),
('Rickety Pinwheel', 27, 'Rare', 'assets/img/killer/addon/rickety_pinwheel.png'),
('Mother’s Comb', 27, 'Rare', 'assets/img/killer/addon/mothers_comb.png'),
('Bloody Fingernails', 27, 'Rare', 'assets/img/killer/addon/bloody_fingernails.png'),
('Well Water', 27, 'Rare', 'assets/img/killer/addon/well_water.png'),
('Telephone', 27, 'Rare', 'assets/img/killer/addon/telephone.png'),
('VCR', 27, 'Very Rare', 'assets/img/killer/addon/vcr.png'),
('Remote Control', 27, 'Very Rare', 'assets/img/killer/addon/remote_control.png'),
('Reiko’s Ring', 27, 'Very Rare', 'assets/img/killer/addon/reikos_ring.png'),
('Iridescent Videotape', 27, 'Ultra Rare', 'assets/img/killer/addon/iridescent_videotape.png'),
('Ring of Fury', 27, 'Ultra Rare', 'assets/img/killer/addon/ring_of_fury.png'),
('Sadako’s Tooth', 27, 'Very Rare', 'assets/img/killer/addon/sadakos_tooth.png'),

-- The Dredge (ID: 28)
('Broken Doll', 28, 'Common', 'assets/img/killer/addon/broken_doll.png'),
('Burnt Letters', 28, 'Common', 'assets/img/killer/addon/burnt_letters.png'),
('Fallen Shingle', 28, 'Common', 'assets/img/killer/addon/fallen_shingle.png'),
('Malthinker’s Skull', 28, 'Common', 'assets/img/killer/addon/malthinkers_skull.png'),
('Worry Stone', 28, 'Uncommon', 'assets/img/killer/addon/worry_stone.png'),
('Wooden Plank', 28, 'Uncommon', 'assets/img/killer/addon/wooden_plank.png'),
('Torn Drawing', 28, 'Uncommon', 'assets/img/killer/addon/torn_drawing.png'),
('Sacrificial Knife', 28, 'Uncommon', 'assets/img/killer/addon/sacrificial_knife.png'),
('Ottomarian Writing', 28, 'Uncommon', 'assets/img/killer/addon/ottomarian_writing.png'),
('War Hammer', 28, 'Rare', 'assets/img/killer/addon/war_hammer.png'),
('Shattered Glass', 28, 'Rare', 'assets/img/killer/addon/shattered_glass.png'),
('Prayer Rope', 28, 'Rare', 'assets/img/killer/addon/prayer_rope.png'),
('Lavalier Microphone', 28, 'Rare', 'assets/img/killer/addon/lavalier_microphone.png'),
('Effigy Doll', 28, 'Rare', 'assets/img/killer/addon/effigy_doll.png'),
('Tainted Mud', 28, 'Very Rare', 'assets/img/killer/addon/tainted_mud.png'),
('Midnight Tome', 28, 'Very Rare', 'assets/img/killer/addon/midnight_tome.png'),
('Field Recorder', 28, 'Very Rare', 'assets/img/killer/addon/field_recorder.png'),
('Boat Key', 28, 'Very Rare', 'assets/img/killer/addon/boat_key.png'),
('Iridescent Wooden Plank', 28, 'Ultra Rare', 'assets/img/killer/addon/iridescent_wooden_plank.png'),
('Malthinker’s Claw', 28, 'Ultra Rare', 'assets/img/killer/addon/malthinkers_claw.png'),

-- The Mastermind (Albert Wesker, ID: 29)
('Video Conference Device', 29, 'Common', 'assets/img/killer/addon/video_conference_device.png'),
('Uroboros Tendril', 29, 'Common', 'assets/img/killer/addon/uroboros_tendril.png'),
('Lab Photo', 29, 'Common', 'assets/img/killer/addon/lab_photo.png'),
('Green Vial', 29, 'Common', 'assets/img/killer/addon/green_vial.png'),
('Unicorn Medallion', 29, 'Uncommon', 'assets/img/killer/addon/unicorn_medallion.png'),
('R.P.D. Shoulder Walkie', 29, 'Uncommon', 'assets/img/killer/addon/rpd_shoulder_walkie.png'),
('Portable Safe', 29, 'Uncommon', 'assets/img/killer/addon/portable_safe.png'),
('Maiden Medallion', 29, 'Uncommon', 'assets/img/killer/addon/maiden_medallion.png'),
('Lion Medallion', 29, 'Uncommon', 'assets/img/killer/addon/lion_medallion.png'),
('Red Herb', 29, 'Rare', 'assets/img/killer/addon/red_herb.png'),
('Leather Gloves', 29, 'Rare', 'assets/img/killer/addon/leather_gloves.png'),
('Jewel Beetle', 29, 'Rare', 'assets/img/killer/addon/jewel_beetle.png'),
('Helicopter Stick', 29, 'Rare', 'assets/img/killer/addon/helicopter_stick.png'),
('Chalice (Gold)', 29, 'Rare', 'assets/img/killer/addon/chalice_gold.png'),
('Uroboros Virus', 29, 'Very Rare', 'assets/img/killer/addon/uroboros_virus.png'),
('Loose Crank', 29, 'Very Rare', 'assets/img/killer/addon/loose_crank.png'),
('Licker Foot', 29, 'Very Rare', 'assets/img/killer/addon/licker_foot.png'),
('Dog Tag', 29, 'Very Rare', 'assets/img/killer/addon/dog_tag.png'),
('Iridescent Uroboros Vial', 29, 'Ultra Rare', 'assets/img/killer/addon/iridescent_uroboros_vial.png'),
('Vial of Serum', 29, 'Ultra Rare', 'assets/img/killer/addon/vial_of_serum.png'),

-- The Knight (Tarhos Kovács, ID: 30)
('Tattered Tabard', 30, 'Common', 'assets/img/killer/addon/tattered_tabard.png'),
('Pillaged Mead', 30, 'Common', 'assets/img/killer/addon/pillaged_mead.png'),
('Knight’s Contract', 30, 'Common', 'assets/img/killer/addon/knights_contract.png'),
('Grim Iron Mask', 30, 'Common', 'assets/img/killer/addon/grim_iron_mask.png'),
('Treated Blade', 30, 'Uncommon', 'assets/img/killer/addon/treated_blade.png'),
('Map of the Realm', 30, 'Uncommon', 'assets/img/killer/addon/map_of_the_realm.png'),
('Ironworker’s Tongs', 30, 'Uncommon', 'assets/img/killer/addon/ironworkers_tongs.png'),
('Flint and Steel', 30, 'Uncommon', 'assets/img/killer/addon/flint_and_steel.png'),
('Broken Hilt', 30, 'Uncommon', 'assets/img/killer/addon/broken_hilt.png'),
('Lightweight Greaves', 30, 'Rare', 'assets/img/killer/addon/lightweight_greaves.png'),
('Healing Poultice', 30, 'Rare', 'assets/img/killer/addon/healing_poultice.png'),
('Chain Mail Fragment', 30, 'Rare', 'assets/img/killer/addon/chain_mail_fragment.png'),
('Blacksmith’s Hammer', 30, 'Rare', 'assets/img/killer/addon/blacksmiths_hammer.png'),
('Battle Axe Head', 30, 'Rare', 'assets/img/killer/addon/battle_axe_head.png'),
('Serrated Jaws', 30, 'Very Rare', 'assets/img/killer/addon/serrated_jaws_knight.png'),
('Cold Steel', 30, 'Very Rare', 'assets/img/killer/addon/cold_steel.png'),
('Call of the Blade', 30, 'Very Rare', 'assets/img/killer/addon/call_of_the_blade.png'),
('Bloodied Gauntlet', 30, 'Very Rare', 'assets/img/killer/addon/bloodied_gauntlet.png'),
('Iridescent Company Banner', 30, 'Ultra Rare', 'assets/img/killer/addon/iridescent_company_banner.png'),
('Crimson Blade', 30, 'Ultra Rare', 'assets/img/killer/addon/crimson_blade.png'),

-- The Skull Merchant (Adriana Imai, ID: 31)
('Shotgun Speakers', 31, 'Common', 'assets/img/killer/addon/shotgun_speakers.png'),
('Prototype Rotor', 31, 'Common', 'assets/img/killer/addon/prototype_rotor.png'),
('Portable Calibration Device', 31, 'Common', 'assets/img/killer/addon/portable_calibration_device.png'),
('Low-Power Mode', 31, 'Common', 'assets/img/killer/addon/low_power_mode.png'),
('Vital Targeting Processor', 31, 'Uncommon', 'assets/img/killer/addon/vital_targeting_processor.png'),
('Supercharge Battery', 31, 'Uncommon', 'assets/img/killer/addon/supercharge_battery.png'),
('Powdered Glass', 31, 'Uncommon', 'assets/img/killer/addon/powdered_glass.png'),
('Loose Screw', 31, 'Uncommon', 'assets/img/killer/addon/loose_screw.png'),
('High-Current Upgrade', 31, 'Uncommon', 'assets/img/killer/addon/high_current_upgrade.png'),
('Ultrasonic Speaker', 31, 'Rare', 'assets/img/killer/addon/ultrasonic_speaker.png'),
('Infrared Upgrade', 31, 'Rare', 'assets/img/killer/addon/infrared_upgrade.png'),
('High-Power Antenna', 31, 'Rare', 'assets/img/killer/addon/high_power_antenna.png'),
('Geo-Tracking Map', 31, 'Rare', 'assets/img/killer/addon/geo_tracking_map.png'),
('Adaptive Lighting', 31, 'Rare', 'assets/img/killer/addon/adaptive_lighting.png'),
('Stereo Remote Mic', 31, 'Very Rare', 'assets/img/killer/addon/stereo_remote_mic.png'),
('Serrated Blades', 31, 'Very Rare', 'assets/img/killer/addon/serrated_blades.png'),
('Remote Diagnostics Tool', 31, 'Very Rare', 'assets/img/killer/addon/remote_diagnostics_tool.png'),
('Expiration Date', 31, 'Very Rare', 'assets/img/killer/addon/expiration_date.png'),
('Iridescent Blueprint', 31, 'Ultra Rare', 'assets/img/killer/addon/iridescent_blueprint.png'),
('Advanced Tracking Module', 31, 'Ultra Rare', 'assets/img/killer/addon/advanced_tracking_module.png'),

-- The Singularity (HUX-A7-13, ID: 32)
('Cremated Ashes', 32, 'Common', 'assets/img/killer/addon/cremated_ashes.png'),
('Cryo Gel', 32, 'Common', 'assets/img/killer/addon/cryo_gel.png'),
('Diagnostic Tool (Repair)', 32, 'Common', 'assets/img/killer/addon/diagnostic_tool_repair.png'),
('Nutritional Slurry', 32, 'Common', 'assets/img/killer/addon/nutritional_slurry.png'),
('Child’s Doll', 32, 'Uncommon', 'assets/img/killer/addon/childs_doll.png'),
('Nano Polymer Skin', 32, 'Uncommon', 'assets/img/killer/addon/nano_polymer_skin.png'),
('Prototype Schematics', 32, 'Uncommon', 'assets/img/killer/addon/prototype_schematics.png'),
('Ration Pack', 32, 'Uncommon', 'assets/img/killer/addon/ration_pack.png'),
('Soma Family Photo', 32, 'Uncommon', 'assets/img/killer/addon/soma_family_photo.png'),
('Crew Manifest', 32, 'Rare', 'assets/img/killer/addon/crew_manifest.png'),
('Denatured Enzyme', 32, 'Rare', 'assets/img/killer/addon/denatured_enzyme.png'),
('Hyperawareness Spray', 32, 'Rare', 'assets/img/killer/addon/hyperawareness_spray.png'),
('Live Wires', 32, 'Rare', 'assets/img/killer/addon/live_wires.png'),
('Viral Canister', 32, 'Rare', 'assets/img/killer/addon/viral_canister.png'),
('Quantum Energy Cell', 32, 'Very Rare', 'assets/img/killer/addon/quantum_energy_cell.png'),
('Diagnostic Tool (Construction)', 32, 'Very Rare', 'assets/img/killer/addon/diagnostic_tool_construction.png'),
('Overclocked Processor', 32, 'Very Rare', 'assets/img/killer/addon/overclocked_processor.png'),
('Synthetic Skin', 32, 'Very Rare', 'assets/img/killer/addon/synthetic_skin.png'),
('Iridescent AI Core', 32, 'Ultra Rare', 'assets/img/killer/addon/iridescent_ai_core.png'),
('Neural Network', 32, 'Ultra Rare', 'assets/img/killer/addon/neural_network.png'),

-- The Xenomorph (ID: 33)
('Acidic Blood', 33, 'Common', 'assets/img/killer/addon/acidic_blood.png'),
('Crew Communicator', 33, 'Common', 'assets/img/killer/addon/crew_communicator.png'),
('Ovomorph', 33, 'Common', 'assets/img/killer/addon/ovomorph.png'),
('Ripley’s Watch', 33, 'Common', 'assets/img/killer/addon/ripleys_watch.png'),
('Broken Key Card', 33, 'Uncommon', 'assets/img/killer/addon/broken_key_card.png'),
('Dallas’ Hat', 33, 'Uncommon', 'assets/img/killer/addon/dallas_hat.png'),
('Emergency Helmet', 33, 'Uncommon', 'assets/img/killer/addon/emergency_helmet.png'),
('Lambert’s Star Map', 33, 'Uncommon', 'assets/img/killer/addon/lamberts_star_map.png'),
('Parker’s Headset', 33, 'Uncommon', 'assets/img/killer/addon/parkers_headset.png'),
('Brett’s Cap', 33, 'Rare', 'assets/img/killer/addon/bretts_cap.png'),
('Cat Carrier', 33, 'Rare', 'assets/img/killer/addon/cat_carrier.png'),
('Chemical Trap', 33, 'Rare', 'assets/img/killer/addon/chemical_trap.png'),
('Kane’s Helmet', 33, 'Rare', 'assets/img/killer/addon/kanes_helmet.png'),
('Motion Tracker', 33, 'Rare', 'assets/img/killer/addon/motion_tracker.png'),
('Ash’s Innards', 33, 'Very Rare', 'assets/img/killer/addon/ashs_innards.png'),
('Emergency Med-Kit', 33, 'Very Rare', 'assets/img/killer/addon/emergency_med_kit.png'),
('Self-Destruct Bolt', 33, 'Very Rare', 'assets/img/killer/addon/self_destruct_bolt.png'),
('Weyland-Yutani ID Tag', 33, 'Very Rare', 'assets/img/killer/addon/weyland_yutani_id_tag.png'),
('Iridescent Queen’s Scale', 33, 'Ultra Rare', 'assets/img/killer/addon/iridescent_queens_scale.png'),
('Ripley’s Remote', 33, 'Ultra Rare', 'assets/img/killer/addon/ripleys_remote.png'),

-- The Good Guy (Chucky, ID: 34)
('Battery Pack', 34, 'Common', 'assets/img/killer/addon/battery_pack.png'),
('Broken Bulb', 34, 'Common', 'assets/img/killer/addon/broken_bulb.png'),
('Jump Rope', 34, 'Common', 'assets/img/killer/addon/jump_rope_good_guy.png'),
('Silk Pillow', 34, 'Common', 'assets/img/killer/addon/silk_pillow.png'),
('Barber’s Razor', 34, 'Uncommon', 'assets/img/killer/addon/barbers_razor.png'),
('Child’s Sneaker', 34, 'Uncommon', 'assets/img/killer/addon/childs_sneaker.png'),
('Plastic Bag', 34, 'Uncommon', 'assets/img/killer/addon/plastic_bag.png'),
('Running Shoes', 34, 'Uncommon', 'assets/img/killer/addon/running_shoes.png'),
('Yardstick', 34, 'Uncommon', 'assets/img/killer/addon/yardstick.png'),
('Electric Carving Knife', 34, 'Rare', 'assets/img/killer/addon/electric_carving_knife.png'),
('Friendship Bracelet', 34, 'Rare', 'assets/img/killer/addon/friendship_bracelet_good_guy.png'),
('Good Guy Box', 34, 'Rare', 'assets/img/killer/addon/good_guy_box.png'),
('Power Drill', 34, 'Rare', 'assets/img/killer/addon/power_drill.png'),
('Strobing Light', 34, 'Rare', 'assets/img/killer/addon/strobing_light.png'),
('Automatic Screwdriver', 34, 'Very Rare', 'assets/img/killer/addon/automatic_screwdriver.png'),
('Doll Eyes', 34, 'Very Rare', 'assets/img/killer/addon/doll_eyes.png'),
('Hard Hat', 34, 'Very Rare', 'assets/img/killer/addon/hard_hat.png'),
('Slashed Tire', 34, 'Very Rare', 'assets/img/killer/addon/slashed_tire.png'),
('Iridescent Amulet', 34, 'Ultra Rare', 'assets/img/killer/addon/iridescent_amulet.png'),
('Tiffany’s Heart', 34, 'Ultra Rare', 'assets/img/killer/addon/tiffanys_heart.png'),

-- The Unknown (ID: 35)
('Broken Toy', 35, 'Common', 'assets/img/killer/addon/broken_toy.png'),
('Frayed Rope', 35, 'Common', 'assets/img/killer/addon/frayed_rope.png'),
('Grainy Photo', 35, 'Common', 'assets/img/killer/addon/grainy_photo.png'),
('Torn Ticket', 35, 'Common', 'assets/img/killer/addon/torn_ticket.png'),
('Cracked Vinyl', 35, 'Uncommon', 'assets/img/killer/addon/cracked_vinyl.png'),
('Faded Booklet', 35, 'Uncommon', 'assets/img/killer/addon/faded_booklet.png'),
('Rusty Locket', 35, 'Uncommon', 'assets/img/killer/addon/rusty_locket.png'),
('Sketched Map', 35, 'Uncommon', 'assets/img/killer/addon/sketched_map.png'),
('Stained Napkin', 35, 'Uncommon', 'assets/img/killer/addon/stained_napkin.png'),
('Burnt Letter', 35, 'Rare', 'assets/img/killer/addon/burnt_letter.png'),
('Child’s Shoe', 35, 'Rare', 'assets/img/killer/addon/childs_shoe.png'),
('Cinema Projector', 35, 'Rare', 'assets/img/killer/addon/cinema_projector.png'),
('Dog Collar', 35, 'Rare', 'assets/img/killer/addon/dog_collar.png'),
('TV Guide', 35, 'Rare', 'assets/img/killer/addon/tv_guide.png'),
('Journal Entry', 35, 'Very Rare', 'assets/img/killer/addon/journal_entry.png'),
('Rabbit’s Foot', 35, 'Very Rare', 'assets/img/killer/addon/rabbits_foot.png'),
('Smashed Glasses', 35, 'Very Rare', 'assets/img/killer/addon/smashed_glasses.png'),
('Warped VHS', 35, 'Very Rare', 'assets/img/killer/addon/warped_vhs.png'),
('Iridescent VHS', 35, 'Ultra Rare', 'assets/img/killer/addon/iridescent_vhs.png'),
('Telephoto Lens', 35, 'Ultra Rare', 'assets/img/killer/addon/telephoto_lens_unknown.png'),

-- The Lich (Vecna, ID: 36)
('Cracked Skull', 36, 'Common', 'assets/img/killer/addon/cracked_skull.png'),
('Crystalline Hilt', 36, 'Common', 'assets/img/killer/addon/crystalline_hilt.png'),
('Pewter Cog', 36, 'Common', 'assets/img/killer/addon/pewter_cog.png'),
('Tome of Dark Magic', 36, 'Common', 'assets/img/killer/addon/tome_of_dark_magic.png'),
('Brass Ring', 36, 'Uncommon', 'assets/img/killer/addon/brass_ring.png'),
('Cloak of Elvenkind', 36, 'Uncommon', 'assets/img/killer/addon/cloak_of_elvenkind.png'),
('Crystal Ball', 36, 'Uncommon', 'assets/img/killer/addon/crystal_ball.png'),
('Vorpal Sword', 36, 'Uncommon', 'assets/img/killer/addon/vorpal_sword.png'),
('Wax Effigy', 36, 'Uncommon', 'assets/img/killer/addon/wax_effigy.png'),
('Amulet of Spell Save', 36, 'Rare', 'assets/img/killer/addon/amulet_of_spell_save.png'),
('Bag of Holding', 36, 'Rare', 'assets/img/killer/addon/bag_of_holding.png'),
('Disintegrate Powder', 36, 'Rare', 'assets/img/killer/addon/disintegrate_powder.png'),
('Potion of Speed', 36, 'Rare', 'assets/img/killer/addon/potion_of_speed.png'),
('Robe of Eyes', 36, 'Rare', 'assets/img/killer/addon/robe_of_eyes.png'),
('Book of Vile Darkness', 36, 'Very Rare', 'assets/img/killer/addon/book_of_vile_darkness.png'),
('Gem of Teleportation', 36, 'Very Rare', 'assets/img/killer/addon/gem_of_teleportation.png'),
('Phylactery Shard', 36, 'Very Rare', 'assets/img/killer/addon/phylactery_shard.png'),
('Ring of Spell Storing', 36, 'Very Rare', 'assets/img/killer/addon/ring_of_spell_storing.png'),
('Iridescent Phylactery', 36, 'Ultra Rare', 'assets/img/killer/addon/iridescent_phylactery.png'),
('Eye of Vecna', 36, 'Ultra Rare', 'assets/img/killer/addon/eye_of_vecna.png'),

-- The Dark Lord (Dracula, ID: 37)
('Wolf Pelt', 37, 'Common', 'assets/img/killer/addon/wolf_pelt.png'),
('Cracked Tombstone', 37, 'Common', 'assets/img/killer/addon/cracked_tombstone.png'),
('Carriage Lantern', 37, 'Common', 'assets/img/killer/addon/carriage_lantern.png'),
('Bloodied Collar', 37, 'Common', 'assets/img/killer/addon/bloodied_collar.png'),
('Torn Saddlebag', 37, 'Uncommon', 'assets/img/killer/addon/torn_saddlebag.png'),
('Silver Bell', 37, 'Uncommon', 'assets/img/killer/addon/silver_bell_dracula.png'),
('Ornate Goblet', 37, 'Uncommon', 'assets/img/killer/addon/ornate_goblet.png'),
('Hunter’s Knife', 37, 'Uncommon', 'assets/img/killer/addon/hunters_knife.png'),
('Bloody Handprint', 37, 'Uncommon', 'assets/img/killer/addon/bloody_handprint.png'),
('Vial of Holy Water', 37, 'Rare', 'assets/img/killer/addon/vial_of_holy_water.png'),
('Stake Hammer', 37, 'Rare', 'assets/img/killer/addon/stake_hammer.png'),
('Ripped Journal', 37, 'Rare', 'assets/img/killer/addon/ripped_journal.png'),
('Raven Feather', 37, 'Rare', 'assets/img/killer/addon/raven_feather.png'),
('Mina’s Letter', 37, 'Rare', 'assets/img/killer/addon/minas_letter.png'),
('Tepes’ Battle Standard', 37, 'Very Rare', 'assets/img/killer/addon/tepes_battle_standard.png'),
('Renfield’s Eye', 37, 'Very Rare', 'assets/img/killer/addon/renfields_eye.png'),
('Lucy’s Ring', 37, 'Very Rare', 'assets/img/killer/addon/lucys_ring.png'),
('Jonathan’s Stake', 37, 'Very Rare', 'assets/img/killer/addon/jonathans_stake.png'),
('Iridescent Reliquary', 37, 'Ultra Rare', 'assets/img/killer/addon/iridescent_reliquary.png'),
('Dracula’s Fangs', 37, 'Ultra Rare', 'assets/img/killer/addon/draculas_fangs.png'),

-- The Houndmaster (Portia Maye, ID: 38)
('Chewed Bone', 38, 'Common', 'assets/img/killer/addon/chewed_bone.png'),
('Dog Whistle', 38, 'Common', 'assets/img/killer/addon/dog_whistle.png'),
('Ragged Collar', 38, 'Common', 'assets/img/killer/addon/ragged_collar.png'),
('Torn Leash', 38, 'Common', 'assets/img/killer/addon/torn_leash.png'),
('Brass Bell', 38, 'Uncommon', 'assets/img/killer/addon/brass_bell.png'),
('Paw Print Patch', 38, 'Uncommon', 'assets/img/killer/addon/paw_print_patch.png'),
('Spiked Collar', 38, 'Uncommon', 'assets/img/killer/addon/spiked_collar.png'),
('Tattered Bow', 38, 'Uncommon', 'assets/img/killer/addon/tattered_bow.png'),
('Worn Horseshoe', 38, 'Uncommon', 'assets/img/killer/addon/worn_horseshoe.png'),
('Bloody Handcuffs', 38, 'Rare', 'assets/img/killer/addon/bloody_handcuffs.png'),
('Dog Training Manual', 38, 'Rare', 'assets/img/killer/addon/dog_training_manual.png'),
('Houndmaster’s Journal', 38, 'Rare', 'assets/img/killer/addon/houndmasters_journal.png'),
('Old Dog Tag', 38, 'Rare', 'assets/img/killer/addon/old_dog_tag.png'),
('Rusty Badge', 38, 'Rare', 'assets/img/killer/addon/rusty_badge.png'),
('Lucky Lead', 38, 'Very Rare', 'assets/img/killer/addon/lucky_lead.png'),
('Sheriff’s Badge', 38, 'Very Rare', 'assets/img/killer/addon/sheriffs_badge.png'),
('Silver Whistle', 38, 'Very Rare', 'assets/img/killer/addon/silver_whistle.png'),
('Torn Wanted Poster', 38, 'Very Rare', 'assets/img/killer/addon/torn_wanted_poster.png'),
('Iridescent Dog Tag', 38, 'Ultra Rare', 'assets/img/killer/addon/iridescent_dog_tag.png'),
('Lucky Collar', 38, 'Ultra Rare', 'assets/img/killer/addon/lucky_collar.png'),

-- The Ghoul (Ken Kaneki, ID: 39)
('Cracked Kagune Fragment', 39, 'Common', 'assets/img/killer/addon/cracked_kagune_fragment.png'),
('Broken Mask', 39, 'Common', 'assets/img/killer/addon/broken_mask.png'),
('Torn Bandage', 39, 'Common', 'assets/img/killer/addon/torn_bandage.png'),
('Bloody Coffee Grounds', 39, 'Common', 'assets/img/killer/addon/bloody_coffee_grounds.png'),
('Rusted Chain', 39, 'Uncommon', 'assets/img/killer/addon/rusted_chain.png'),
('Ghoul’s Journal', 39, 'Uncommon', 'assets/img/killer/addon/ghouls_journal.png'),
('Flesh Scrap', 39, 'Uncommon', 'assets/img/killer/addon/flesh_scrap.png'),
('Cracked Quinque', 39, 'Uncommon', 'assets/img/killer/addon/cracked_quinque.png'),
('Torn Eyepatch', 39, 'Uncommon', 'assets/img/killer/addon/torn_eyepatch.png'),
('Bloodied Mask', 39, 'Rare', 'assets/img/killer/addon/bloodied_mask.png'),
('Kagune Shard', 39, 'Rare', 'assets/img/killer/addon/kagune_shard.png'),
('Torn Manuscript', 39, 'Rare', 'assets/img/killer/addon/torn_manuscript.png'),
('Ghoul’s Coffee Mug', 39, 'Rare', 'assets/img/killer/addon/ghouls_coffee_mug.png'),
('Stained Bandage', 39, 'Rare', 'assets/img/killer/addon/stained_bandage.png'),
('Tokyo Ghoul Novel', 39, 'Very Rare', 'assets/img/killer/addon/tokyo_ghoul_novel.png'),
('Centipede Husk', 39, 'Very Rare', 'assets/img/killer/addon/centipede_husk.png'),
('Kaneki’s Mask', 39, 'Very Rare', 'assets/img/killer/addon/kanekis_mask.png'),
('Quinque Fragment', 39, 'Very Rare', 'assets/img/killer/addon/quinque_fragment.png'),
('Iridescent Kagune', 39, 'Ultra Rare', 'assets/img/killer/addon/iridescent_kagune.png'),
('Kaneki’s Eye', 39, 'Ultra Rare', 'assets/img/killer/addon/kanekis_eye.png'),

-- The Animatronic (William Afton, ID: 40)
('Broken Circuit Board', 40, 'Common', 'assets/img/killer/addon/broken_circuit_board.png'),
('Rusted Spring', 40, 'Common', 'assets/img/killer/addon/rusted_spring.png'),
('Fazbear Token', 40, 'Common', 'assets/img/killer/addon/fazbear_token.png'),
('Torn Poster', 40, 'Common', 'assets/img/killer/addon/torn_poster.png'),
('Cracked Animatronic Eye', 40, 'Uncommon', 'assets/img/killer/addon/cracked_animatronic_eye.png'),
('Foxy’s Hook', 40, 'Uncommon', 'assets/img/killer/addon/foxys_hook.png'),
('Freddy’s Hat', 40, 'Uncommon', 'assets/img/killer/addon/freddys_hat.png'),
('Pizzeria Keychain', 40, 'Uncommon', 'assets/img/killer/addon/pizzeria_keychain.png'),
('Worn Ticket Stub', 40, 'Uncommon', 'assets/img/killer/addon/worn_ticket_stub.png'),
('Burnt Plushie', 40, 'Rare', 'assets/img/killer/addon/burnt_plushie.png'),
('Chica’s Bib', 40, 'Rare', 'assets/img/killer/addon/chicas_bib.png'),
('Fazbear Music Box', 40, 'Rare', 'assets/img/killer/addon/fazbear_music_box.png'),
('Security Badge', 40, 'Rare', 'assets/img/killer/addon/security_badge.png'),
('Springlock Screw', 40, 'Rare', 'assets/img/killer/addon/springlock_screw.png'),
('Afton’s Blueprints', 40, 'Very Rare', 'assets/img/killer/addon/aftons_blueprints.png'),
('Broken Endoskeleton', 40, 'Very Rare', 'assets/img/killer/addon/broken_endoskeleton.png'),
('Fazbear Circuitry', 40, 'Very Rare', 'assets/img/killer/addon/fazbear_circuitry.png'),
('Springtrap’s Ear', 40, 'Very Rare', 'assets/img/killer/addon/springtraps_ear.png'),
('Iridescent Springlock', 40, 'Ultra Rare', 'assets/img/killer/addon/iridescent_springlock.png'),
('Afton’s Legacy', 40, 'Ultra Rare', 'assets/img/killer/addon/aftons_legacy.png');