INSERT INTO Killer_Perks (name, killer_id, icon) VALUES
('A Nurse''s Calling', (SELECT id FROM Killers WHERE killer_name = 'The Nurse'), 'assets/img/killer/perk/a_nurses_calling.png'),
('Agitation', (SELECT id FROM Killers WHERE killer_name = 'The Trapper'), 'assets/img/killer/perk/agitation.png'),
('Alien Instinct', (SELECT id FROM Killers WHERE killer_name = 'The Xenomorph'), 'assets/img/killer/perk/alien_instinct.png'),
('All-Shaking Thunder', (SELECT id FROM Killers WHERE killer_name = 'The Houndmaster'), 'assets/img/killer/perk/all_shaking_thunder.png'),
('Awakened Awareness', (SELECT id FROM Killers WHERE killer_name = 'The Mastermind'), 'assets/img/killer/perk/awakened_awareness.png'),
('Bamboozle', (SELECT id FROM Killers WHERE killer_name = 'The Clown'), 'assets/img/killer/perk/bamboozle.png'),
('Barbecue & Chilli', (SELECT id FROM Killers WHERE killer_name = 'The Cannibal'), 'assets/img/killer/perk/barbecue_and_chilli.png'),
('Batteries Included', (SELECT id FROM Killers WHERE killer_name = 'The Good Guy'), 'assets/img/killer/perk/batteries_included.png'),
('Beast of Prey', (SELECT id FROM Killers WHERE killer_name = 'The Huntress'), 'assets/img/killer/perk/beast_of_prey.png'),
('Bitter Murmur', NULL, 'assets/img/killer/perk/bitter_murmur.png'),
('Blood Echo', (SELECT id FROM Killers WHERE killer_name = 'The Oni'), 'assets/img/killer/perk/blood_echo.png'),
('Blood Warden', (SELECT id FROM Killers WHERE killer_name = 'The Nightmare'), 'assets/img/killer/perk/blood_warden.png'),
('Bloodhound', (SELECT id FROM Killers WHERE killer_name = 'The Wraith'), 'assets/img/killer/perk/bloodhound.png'),
('Brutal Strength', (SELECT id FROM Killers WHERE killer_name = 'The Trapper'), 'assets/img/killer/perk/brutal_strength.png'),
('Call of Brine', (SELECT id FROM Killers WHERE killer_name = 'The Onryō'), 'assets/img/killer/perk/call_of_brine.png'),
('Corrupt Intervention', (SELECT id FROM Killers WHERE killer_name = 'The Plague'), 'assets/img/killer/perk/corrupt_intervention.png'),
('Coulrophobia', (SELECT id FROM Killers WHERE killer_name = 'The Clown'), 'assets/img/killer/perk/coulrophobia.png'),
('Coup de Grâce', (SELECT id FROM Killers WHERE killer_name = 'The Twins'), 'assets/img/killer/perk/coup_de_grace.png'),
('Cruel Limits', (SELECT id FROM Killers WHERE killer_name = 'The Demogorgon'), 'assets/img/killer/perk/cruel_limits.png'),
('Dark Arrogance', (SELECT id FROM Killers WHERE killer_name = 'The Lich'), 'assets/img/killer/perk/dark_arrogance.png'),
('Dark Devotion', (SELECT id FROM Killers WHERE killer_name = 'The Plague'), 'assets/img/killer/perk/dark_devotion.png'),
('Darkness Revealed', (SELECT id FROM Killers WHERE killer_name = 'The Dredge'), 'assets/img/killer/perk/darkness_revealed.png'),
('Dead Man''s Switch', (SELECT id FROM Killers WHERE killer_name = 'The Deathslinger'), 'assets/img/killer/perk/dead_mans_switch.png'),
('Deathbound', (SELECT id FROM Killers WHERE killer_name = 'The Executioner'), 'assets/img/killer/perk/deathbound.png'),
('Deerstalker', NULL, 'assets/img/killer/perk/deerstalker.png'),
('Discordance', (SELECT id FROM Killers WHERE killer_name = 'The Legion'), 'assets/img/killer/perk/discordance.png'),
('Dissolution', (SELECT id FROM Killers WHERE killer_name = 'The Dredge'), 'assets/img/killer/perk/dissolution.png'),
('Distressing', NULL, 'assets/img/killer/perk/distressing.png'),
('Dominance', (SELECT id FROM Killers WHERE killer_name = 'The Dark Lord'), 'assets/img/killer/perk/dominance.png'),
('Dragon''s Grip', (SELECT id FROM Killers WHERE killer_name = 'The Blight'), 'assets/img/killer/perk/dragons_grip.png'),
('Dying Light', (SELECT id FROM Killers WHERE killer_name = 'The Shape'), 'assets/img/killer/perk/dying_light.png'),
('Enduring', (SELECT id FROM Killers WHERE killer_name = 'The Hillbilly'), 'assets/img/killer/perk/enduring.png'),
('Eruption', (SELECT id FROM Killers WHERE killer_name = 'The Nemesis'), 'assets/img/killer/perk/eruption.png'),
('Fire Up', (SELECT id FROM Killers WHERE killer_name = 'The Nightmare'), 'assets/img/killer/perk/fire_up.png'),
('Forced Hesitation', (SELECT id FROM Killers WHERE killer_name = 'The Singularity'), 'assets/img/killer/perk/forced_hesitation.png'),
('Forced Penance', (SELECT id FROM Killers WHERE killer_name = 'The Executioner'), 'assets/img/killer/perk/forced_penance.png'),
('Forever Entwined', (SELECT id FROM Killers WHERE killer_name = 'The Ghoul'), 'assets/img/killer/perk/forever_entwined.png'),
('Franklin''s Demise', (SELECT id FROM Killers WHERE killer_name = 'The Cannibal'), 'assets/img/killer/perk/franklins_demise.png'),
('Friends ''til the End', (SELECT id FROM Killers WHERE killer_name = 'The Good Guy'), 'assets/img/killer/perk/friends_til_the_end.png'),
('Furtive Chase', (SELECT id FROM Killers WHERE killer_name = 'The Ghost Face'), 'assets/img/killer/perk/furtive_chase.png'),
('Game Afoot', (SELECT id FROM Killers WHERE killer_name = 'The Skull Merchant'), 'assets/img/killer/perk/game_afoot.png'),
('Gearhead', (SELECT id FROM Killers WHERE killer_name = 'The Deathslinger'), 'assets/img/killer/perk/gearhead.png'),
('Genetic Limits', (SELECT id FROM Killers WHERE killer_name = 'The Singularity'), 'assets/img/killer/perk/genetic_limits.png'),
('Grim Embrace', (SELECT id FROM Killers WHERE killer_name = 'The Artist'), 'assets/img/killer/perk/grim_embrace.png'),
('Haywire', (SELECT id FROM Killers WHERE killer_name = 'The Animatronic'), 'assets/img/killer/perk/haywire.png'),
('Help Wanted', (SELECT id FROM Killers WHERE killer_name = 'The Animatronic'), 'assets/img/killer/perk/help_wanted.png'),
('Hex: Blood Favour', (SELECT id FROM Killers WHERE killer_name = 'The Blight'), 'assets/img/killer/perk/hex_blood_favour.png'),
('Hex: Crowd Control', (SELECT id FROM Killers WHERE killer_name = 'The Trickster'), 'assets/img/killer/perk/hex_crowd_control.png'),
('Hex: Devour Hope', (SELECT id FROM Killers WHERE killer_name = 'The Hag'), 'assets/img/killer/perk/hex_devour_hope.png'),
('Hex: Face the Darkness', (SELECT id FROM Killers WHERE killer_name = 'The Knight'), 'assets/img/killer/perk/hex_face_the_darkness.png'),
('Hex: Fortune''s Fool', (SELECT id FROM Killers WHERE killer_name = 'The Cenobite'), 'assets/img/killer/perk/hex_fortunes_fool .png'),
('Hex: Haunted Ground', (SELECT id FROM Killers WHERE killer_name = 'The Spirit'), 'assets/img/killer/perk/hex_haunted_ground.png'),
('Hex: Huntress Lullaby', (SELECT id FROM Killers WHERE killer_name = 'The Huntress'), 'assets/img/killer/perk/hex_huntress_lullaby.png'),
('Hex: No One Escapes Death', NULL, 'assets/img/killer/perk/hex_no_one_escapes_death.png'),
('Hex: Nothing But Misery', (SELECT id FROM Killers WHERE killer_name = 'The Ghoul'), 'assets/img/killer/perk/hex_nothing_but_misery.png'),
('Hex: Pentimento', (SELECT id FROM Killers WHERE killer_name = 'The Artist'), 'assets/img/killer/perk/hex_pentimento.png'),
('Hex: Retribution', (SELECT id FROM Killers WHERE killer_name = 'The Deathslinger'), 'assets/img/killer/perk/hex_retribution.png'),
('Hex: Ruin', (SELECT id FROM Killers WHERE killer_name = 'The Hag'), 'assets/img/killer/perk/hex_ruin.png'),
('Hex: The Third Seal', (SELECT id FROM Killers WHERE killer_name = 'The Hag'), 'assets/img/killer/perk/hex_the_third_seal.png'),
('Hex: Thrill of the Hunt', NULL, 'assets/img/killer/perk/hex_thrill_of_the_hunt.png'),
('Hex: Two Can Play', (SELECT id FROM Killers WHERE killer_name = 'The Good Guy'), 'assets/img/killer/perk/hex_two_can_play.png'),
('Hex: Undying', (SELECT id FROM Killers WHERE killer_name = 'The Blight'), 'assets/img/killer/perk/hex_undying.png'),
('Hex: Wretched Fate', (SELECT id FROM Killers WHERE killer_name = 'The Dark Lord'), 'assets/img/killer/perk/hex_wretched_fate.png'),
('Hoarder', (SELECT id FROM Killers WHERE killer_name = 'The Twins'), 'assets/img/killer/perk/hoarder.png'),
('Hubris', (SELECT id FROM Killers WHERE killer_name = 'The Knight'), 'assets/img/killer/perk/hubris.png'),
('Human Greed', (SELECT id FROM Killers WHERE killer_name = 'The Dark Lord'), 'assets/img/killer/perk/human_greed.png'),
('Hysteria', (SELECT id FROM Killers WHERE killer_name = 'The Nemesis'), 'assets/img/killer/perk/hysteria.png'),
('I''m All Ears', (SELECT id FROM Killers WHERE killer_name = 'The Ghost Face'), 'assets/img/killer/perk/im_all_ears.png'),
('Infectious Fright', (SELECT id FROM Killers WHERE killer_name = 'The Plague'), 'assets/img/killer/perk/infectious_fright.png'),
('Insidious', NULL, 'assets/img/killer/perk/insidious.png'),
('Iron Grasp', NULL, 'assets/img/killer/perk/iron_grasp.png'),
('Iron Maiden', (SELECT id FROM Killers WHERE killer_name = 'The Legion'), 'assets/img/killer/perk/iron_maiden.png'),
('Knock Out', (SELECT id FROM Killers WHERE killer_name = 'The Cannibal'), 'assets/img/killer/perk/knock_out.png'),
('Languid Touch', (SELECT id FROM Killers WHERE killer_name = 'The Lich'), 'assets/img/killer/perk/languid_touch.png'),
('Lethal Pursuer', (SELECT id FROM Killers WHERE killer_name = 'The Nemesis'), 'assets/img/killer/perk/lethal_pursuer.png'),
('Leverage', (SELECT id FROM Killers WHERE killer_name = 'The Skull Merchant'), 'assets/img/killer/perk/leverage.png'),
('Lightborn', (SELECT id FROM Killers WHERE killer_name = 'The Hillbilly'), 'assets/img/killer/perk/lightborn.png'),
('Machine Learning', (SELECT id FROM Killers WHERE killer_name = 'The Singularity'), 'assets/img/killer/perk/machine_learning.png'),
('Mad Grit', (SELECT id FROM Killers WHERE killer_name = 'The Legion'), 'assets/img/killer/perk/mad_grit.png'),
('Make Your Choice', (SELECT id FROM Killers WHERE killer_name = 'The Pig'), 'assets/img/killer/perk/make_your_choice.png'),
('Merciless Storm', (SELECT id FROM Killers WHERE killer_name = 'The Onryō'), 'assets/img/killer/perk/merciless_storm.png'),
('Mindbreaker', (SELECT id FROM Killers WHERE killer_name = 'The Demogorgon'), 'assets/img/killer/perk/mindbreaker.png'),
('Monitor & Abuse', (SELECT id FROM Killers WHERE killer_name = 'The Doctor'), 'assets/img/killer/perk/monitor_and_abuse.png'),
('Nemesis', (SELECT id FROM Killers WHERE killer_name = 'The Oni'), 'assets/img/killer/perk/nemesis.png'),
('No Holds Barred', (SELECT id FROM Killers WHERE killer_name = 'The Cenobite'), 'assets/img/killer/perk/no_holds_barred.png'),
('No Quarter', (SELECT id FROM Killers WHERE killer_name = 'The Houndmaster'), 'assets/img/killer/perk/no_quarter.png'),
('No Way Out', (SELECT id FROM Killers WHERE killer_name = 'The Trickster'), 'assets/img/killer/perk/no_way_out.png'),
('None Are Free', (SELECT id FROM Killers WHERE killer_name = 'The Ghoul'), 'assets/img/killer/perk/none_are_free.png'),
('Nowhere to Hide', (SELECT id FROM Killers WHERE killer_name = 'The Knight'), 'assets/img/killer/perk/nowhere_to_hide.png'),
('Oppression', (SELECT id FROM Killers WHERE killer_name = 'The Twins'), 'assets/img/killer/perk/oppression.png'),
('Overcharge', (SELECT id FROM Killers WHERE killer_name = 'The Doctor'), 'assets/img/killer/perk/overcharge.png'),
('Overwhelming Presence', (SELECT id FROM Killers WHERE killer_name = 'The Doctor'), 'assets/img/killer/perk/overwhelming_presence.png'),
('Phantom Fear', (SELECT id FROM Killers WHERE killer_name = 'The Animatronic'), 'assets/img/killer/perk/phantom_fear.png'),
('Play With Your Food', (SELECT id FROM Killers WHERE killer_name = 'The Shape'), 'assets/img/killer/perk/play_with_your_food.png'),
('Pop Goes the Weasel', (SELECT id FROM Killers WHERE killer_name = 'The Clown'), 'assets/img/killer/perk/pop_goes_the_weasel.png'),
('Predator', (SELECT id FROM Killers WHERE killer_name = 'The Wraith'), 'assets/img/killer/perk/predator.png'),
('Rancor', (SELECT id FROM Killers WHERE killer_name = 'The Spirit'), 'assets/img/killer/perk/rancor.png'),
('Rapid Brutality', (SELECT id FROM Killers WHERE killer_name = 'The Xenomorph'), 'assets/img/killer/perk/rapid_brutality.png'),
('Remember Me', (SELECT id FROM Killers WHERE killer_name = 'The Nightmare'), 'assets/img/killer/perk/remember_me.png'),
('Save the Best for Last', (SELECT id FROM Killers WHERE killer_name = 'The Shape'), 'assets/img/killer/perk/save_the_best_for_last.png'),
('Scourge Hook: Floods of Rage', (SELECT id FROM Killers WHERE killer_name = 'The Onryō'), 'assets/img/killer/perk/scourge_hook_floods_of_rage.png'),
('Scourge Hook: Hangman''s Trick', (SELECT id FROM Killers WHERE killer_name = 'The Pig'), 'assets/img/killer/perk/scourge_hook_hangmans_trick.png'),
('Scourge Hook: Jagged Compass', (SELECT id FROM Killers WHERE killer_name = 'The Houndmaster'), 'assets/img/killer/perk/scourge_hook_jagged_compass.png'),
('Scourge Hook: Monstrous Shrine', NULL, 'assets/img/killer/perk/scourge_hook_monstrous_shrine.png'),
('Scourge Hook: Pain Resonance', (SELECT id FROM Killers WHERE killer_name = 'The Artist'), 'assets/img/killer/perk/scourge_hook_pain_resonance.png'),
('Scourge Hook: Weeping Wounds', (SELECT id FROM Killers WHERE killer_name = 'The Cenobite'), 'assets/img/killer/perk/scourge_hook_weeping_wounds.png'),
('Septic Touch', (SELECT id FROM Killers WHERE killer_name = 'The Dredge'), 'assets/img/killer/perk/septic_touch.png'),
('Shadowborn', (SELECT id FROM Killers WHERE killer_name = 'The Wraith'), 'assets/img/killer/perk/shadowborn.png'),
('Shattered Hope', NULL, 'assets/img/killer/perk/shattered_hope.png'),
('Sloppy Butcher', NULL, 'assets/img/killer/perk/sloppy_butcher.png'),
('Spies from the Shadows', NULL, 'assets/img/killer/perk/spies_from_the_shadows.png'),
('Spirit Fury', (SELECT id FROM Killers WHERE killer_name = 'The Spirit'), 'assets/img/killer/perk/spirit_fury.png'),
('Starstruck', (SELECT id FROM Killers WHERE killer_name = 'The Trickster'), 'assets/img/killer/perk/starstruck.png'),
('Stridor', (SELECT id FROM Killers WHERE killer_name = 'The Nurse'), 'assets/img/killer/perk/stridor.png'),
('Superior Anatomy', (SELECT id FROM Killers WHERE killer_name = 'The Mastermind'), 'assets/img/killer/perk/superior_anatomy.png'),
('Surge', (SELECT id FROM Killers WHERE killer_name = 'The Demogorgon'), 'assets/img/killer/perk/surge.png'),
('Surveillance', (SELECT id FROM Killers WHERE killer_name = 'The Pig'), 'assets/img/killer/perk/surveillance.png'),
('THWACK!', (SELECT id FROM Killers WHERE killer_name = 'The Skull Merchant'), 'assets/img/killer/perk/thwack.png'),
('Terminus', (SELECT id FROM Killers WHERE killer_name = 'The Mastermind'), 'assets/img/killer/perk/terminus.png'),
('Territorial Imperative', (SELECT id FROM Killers WHERE killer_name = 'The Huntress'), 'assets/img/killer/perk/territorial_imperative.png'),
('Thanatophobia', (SELECT id FROM Killers WHERE killer_name = 'The Nurse'), 'assets/img/killer/perk/thanatophobia.png'),
('Thrilling Tremors', (SELECT id FROM Killers WHERE killer_name = 'The Ghost Face'), 'assets/img/killer/perk/thrilling_tremors.png'),
('Tinkerer', (SELECT id FROM Killers WHERE killer_name = 'The Hillbilly'), 'assets/img/killer/perk/tinkerer.png'),
('Trail of Torment', (SELECT id FROM Killers WHERE killer_name = 'The Executioner'), 'assets/img/killer/perk/trail_of_torment.png'),
('Ultimate Weapon', (SELECT id FROM Killers WHERE killer_name = 'The Xenomorph'), 'assets/img/killer/perk/ultimate_weapon.png'),
('Unbound', (SELECT id FROM Killers WHERE killer_name = 'The Unknown'), 'assets/img/killer/perk/unbound.png'),
('Undone', (SELECT id FROM Killers WHERE killer_name = 'The Unknown'), 'assets/img/killer/perk/undone.png'),
('Unforeseen', (SELECT id FROM Killers WHERE killer_name = 'The Unknown'), 'assets/img/killer/perk/unforeseen.png'),
('Unnerving Presence', (SELECT id FROM Killers WHERE killer_name = 'The Trapper'), 'assets/img/killer/perk/unnerving_presence.png'),
('Unrelenting', NULL, 'assets/img/killer/perk/unrelenting.png'),
('Weave Attunement', (SELECT id FROM Killers WHERE killer_name = 'The Lich'), 'assets/img/killer/perk/weave_attunement.png'),
('Whispers', NULL, 'assets/img/killer/perk/whispers.png'),
('Zanshin Tactics', (SELECT id FROM Killers WHERE killer_name = 'The Oni'), 'assets/img/killer/perk/zanshin_tactics.png');