INSERT INTO Killer_Perks (name, killer_id, icon) VALUES
('A Nurse''s Calling', (SELECT id FROM Killers WHERE killer_name = 'The Nurse'), 'assets/img/killer/perks/a_nurses_calling.png'),
('Agitation', (SELECT id FROM Killers WHERE killer_name = 'The Trapper'), 'assets/img/killer/perks/agitation.png'),
('All-Shaking Thunder', (SELECT id FROM Killers WHERE killer_name = 'The Houndmaster'), 'assets/img/killer/perks/all_shaking_thunder.png'),
('Awakened Awareness', (SELECT id FROM Killers WHERE killer_name = 'The Mastermind'), 'assets/img/killer/perks/awakened_awareness.png'),
('Bamboozle', (SELECT id FROM Killers WHERE killer_name = 'The Clown'), 'assets/img/killer/perks/bamboozle.png'),
('Barbecue & Chilli', (SELECT id FROM Killers WHERE killer_name = 'The Cannibal'), 'assets/img/killer/perks/barbecue_and_chilli.png'),
('Beast of Prey', (SELECT id FROM Killers WHERE killer_name = 'The Huntress'), 'assets/img/killer/perks/beast_of_prey.png'),
('Bitter Murmur', NULL, 'assets/img/killer/perks/bitter_murmur.png'),
('Blood Echo', (SELECT id FROM Killers WHERE killer_name = 'The Oni'), 'assets/img/killer/perks/blood_echo.png'),
('Blood Warden', (SELECT id FROM Killers WHERE killer_name = 'The Nightmare'), 'assets/img/killer/perks/blood_warden.png'),
('Bloodhound', (SELECT id FROM Killers WHERE killer_name = 'The Wraith'), 'assets/img/killer/perks/bloodhound.png'),
('Brutal Strength', (SELECT id FROM Killers WHERE killer_name = 'The Trapper'), 'assets/img/killer/perks/brutal_strength.png'),
('Call of Brine', (SELECT id FROM Killers WHERE killer_name = 'The Onryō'), 'assets/img/killer/perks/call_of_brine.png'),
('Claustrophobia', (SELECT id FROM Killers WHERE killer_name = 'The Trickster'), 'assets/img/killer/perks/claustrophobia.png'),
('Corrupt Intervention', (SELECT id FROM Killers WHERE killer_name = 'The Plague'), 'assets/img/killer/perks/corrupt_intervention.png'),
('Coulrophobia', (SELECT id FROM Killers WHERE killer_name = 'The Clown'), 'assets/img/killer/perks/coulrophobia.png'),
('Cruel Limits', (SELECT id FROM Killers WHERE killer_name = 'The Demogorgon'), 'assets/img/killer/perks/cruel_limits.png'),
('Dark Devotion', (SELECT id FROM Killers WHERE killer_name = 'The Plague'), 'assets/img/killer/perks/dark_devotion.png'),
('Darkness Revealed', (SELECT id FROM Killers WHERE killer_name = 'The Dredge'), 'assets/img/killer/perks/darkness_revealed.png'),
('Dead Man''s Switch', (SELECT id FROM Killers WHERE killer_name = 'The Deathslinger'), 'assets/img/killer/perks/dead_mans_switch.png'),
('Deadlock', (SELECT id FROM Killers WHERE killer_name = 'The Cenobite'), 'assets/img/killer/perks/deadlock.png'),
('Deerstalker', NULL, 'assets/img/killer/perks/deerstalker.png'),
('Discordance', (SELECT id FROM Killers WHERE killer_name = 'The Legion'), 'assets/img/killer/perks/discordance.png'),
('Dissolution', (SELECT id FROM Killers WHERE killer_name = 'The Dredge'), 'assets/img/killer/perks/dissolution.png'),
('Distressing', NULL, 'assets/img/killer/perks/distressing.png'),
('Dominance', (SELECT id FROM Killers WHERE killer_name = 'The Skull Merchant'), 'assets/img/killer/perks/dominance.png'),
('Dragon''s Grip', (SELECT id FROM Killers WHERE killer_name = 'The Blight'), 'assets/img/killer/perks/dragons_grip.png'),
('Dying Light', (SELECT id FROM Killers WHERE killer_name = 'The Shape'), 'assets/img/killer/perks/dying_light.png'),
('Enduring', (SELECT id FROM Killers WHERE killer_name = 'The Hillbilly'), 'assets/img/killer/perks/enduring.png'),
('Eruption', (SELECT id FROM Killers WHERE killer_name = 'The Onryō'), 'assets/img/killer/perks/eruption.png'),
('Fearmonger', (SELECT id FROM Killers WHERE killer_name = 'The Legion'), 'assets/img/killer/perks/fearmonger.png'),
('Fire Up', (SELECT id FROM Killers WHERE killer_name = 'The Nightmare'), 'assets/img/killer/perks/fire_up.png'),
('Forced Hesitation', (SELECT id FROM Killers WHERE killer_name = 'The Legion'), 'assets/img/killer/perks/forced_hesitation.png'),
('Forced Penance', (SELECT id FROM Killers WHERE killer_name = 'The Executioner'), 'assets/img/killer/perks/forced_penance.png'),
('Franklin''s Demise', (SELECT id FROM Killers WHERE killer_name = 'The Cannibal'), 'assets/img/killer/perks/franklins_demise.png'),
('Friends ''til the End', (SELECT id FROM Killers WHERE killer_name = 'The Good Guy'), 'assets/img/killer/perks/friends_til_the_end.png'),
('Furtive Chase', (SELECT id FROM Killers WHERE killer_name = 'The Ghost Face'), 'assets/img/killer/perks/furtive_chase.png'),
('Game Afoot', (SELECT id FROM Killers WHERE killer_name = 'The Ghost Face'), 'assets/img/killer/perks/game_afoot.png'),
('Gearhead', (SELECT id FROM Killers WHERE killer_name = 'The Deathslinger'), 'assets/img/killer/perks/gearhead.png'),
('Genetic Limits', (SELECT id FROM Killers WHERE killer_name = 'The Twins'), 'assets/img/killer/perks/genetic_limits.png'),
('Grim Embrace', (SELECT id FROM Killers WHERE killer_name = 'The Artist'), 'assets/img/killer/perks/grim_embrace.png'),
('Hex: Blood Favour', (SELECT id FROM Killers WHERE killer_name = 'The Blight'), 'assets/img/killer/perks/hex_blood_favour.png'),
('Hex: Crowd Control', (SELECT id FROM Killers WHERE killer_name = 'The Trickster'), 'assets/img/killer/perks/hex_crowd_control.png'),
('Hex: Devour Hope', (SELECT id FROM Killers WHERE killer_name = 'The Hag'), 'assets/img/killer/perks/hex_devour_hope.png'),
('Hex: Face the Darkness', (SELECT id FROM Killers WHERE killer_name = 'The Dredge'), 'assets/img/killer/perks/hex_face_the_darkness.png'),
('Hex: Haunted Ground', (SELECT id FROM Killers WHERE killer_name = 'The Spirit'), 'assets/img/killer/perks/hex_haunted_ground.png'),
('Hex: Huntress Lullaby', (SELECT id FROM Killers WHERE killer_name = 'The Huntress'), 'assets/img/killer/perks/hex_huntress_lullaby.png'),
('Hex: No One Escapes Death', NULL, 'assets/img/killer/perks/hex_no_one_escapes_death.png'),
('Hex: Pentimento', (SELECT id FROM Killers WHERE killer_name = 'The Artist'), 'assets/img/killer/perks/hex_pentimento.png'),
('Hex: Plaything', (SELECT id FROM Killers WHERE killer_name = 'The Cenobite'), 'assets/img/killer/perks/hex_plaything.png'),
('Hex: Retribution', (SELECT id FROM Killers WHERE killer_name = 'The Deathslinger'), 'assets/img/killer/perks/hex_retribution.png'),
('Hex: Ruin', (SELECT id FROM Killers WHERE killer_name = 'The Hag'), 'assets/img/killer/perks/hex_ruin.png'),
('Hex: The Third Seal', (SELECT id FROM Killers WHERE killer_name = 'The Hag'), 'assets/img/killer/perks/hex_the_third_seal.png'),
('Hex: Thrill of the Hunt', (SELECT id FROM Killers WHERE killer_name = 'The Huntress'), 'assets/img/killer/perks/hex_thrill_of_the_hunt.png'),
('Hex: Two Can Play', (SELECT id FROM Killers WHERE killer_name = 'The Good Guy'), 'assets/img/killer/perks/hex_two_can_play.png'),
('Hex: Undying', (SELECT id FROM Killers WHERE killer_name = 'The Blight'), 'assets/img/killer/perks/hex_undying.png'),
('Hoarder', (SELECT id FROM Killers WHERE killer_name = 'The Twins'), 'assets/img/killer/perks/hoarder.png'),
('Hysteria', (SELECT id FROM Killers WHERE killer_name = 'The Nemesis'), 'assets/img/killer/perks/hysteria.png'),
('I''m All Ears', (SELECT id FROM Killers WHERE killer_name = 'The Ghost Face'), 'assets/img/killer/perks/im_all_ears.png'),
('Infectious Fright', (SELECT id FROM Killers WHERE killer_name = 'The Plague'), 'assets/img/killer/perks/infectious_fright.png'),
('Insidious', NULL, 'assets/img/killer/perks/insidious.png'),
('Iron Grasp', NULL, 'assets/img/killer/perks/iron_grasp.png'),
('Iron Maiden', (SELECT id FROM Killers WHERE killer_name = 'The Legion'), 'assets/img/killer/perks/iron_maiden.png'),
('Jolt', NULL, 'assets/img/killer/perks/jolt.png'),
('Knock Out', (SELECT id FROM Killers WHERE killer_name = 'The Cannibal'), 'assets/img/killer/perks/knock_out.png'),
('Languid Touch', (SELECT id FROM Killers WHERE killer_name = 'The Xenomorph'), 'assets/img/killer/perks/languid_touch.png'),
('Lethal Pursuer', (SELECT id FROM Killers WHERE killer_name = 'The Nemesis'), 'assets/img/killer/perks/lethal_pursuer.png'),
('Leverage', (SELECT id FROM Killers WHERE killer_name = 'The Skull Merchant'), 'assets/img/killer/perks/leverage.png'),
('Lightborn', (SELECT id FROM Killers WHERE killer_name = 'The Hillbilly'), 'assets/img/killer/perks/lightborn.png'),
('Machine Learning', (SELECT id FROM Killers WHERE killer_name = 'The Singularity'), 'assets/img/killer/perks/machine_learning.png'),
('Mad Grit', (SELECT id FROM Killers WHERE killer_name = 'The Legion'), 'assets/img/killer/perks/mad_grit.png'),
('Make Your Choice', (SELECT id FROM Killers WHERE killer_name = 'The Pig'), 'assets/img/killer/perks/make_your_choice.png'),
('Monitor & Abuse', (SELECT id FROM Killers WHERE killer_name = 'The Doctor'), 'assets/img/killer/perks/monitor_and_abuse.png'),
('Monstrous Shrine', NULL, 'assets/img/killer/perks/monstrous_shrine.png'),
('Nemesis', (SELECT id FROM Killers WHERE killer_name = 'The Nemesis'), 'assets/img/killer/perks/nemesis.png'),
('No Way Out', (SELECT id FROM Killers WHERE killer_name = 'The Trickster'), 'assets/img/killer/perks/no_way_out.png'),
('Nowhere to Hide', (SELECT id FROM Killers WHERE killer_name = 'The Knight'), 'assets/img/killer/perks/nowhere_to_hide.png'),
('Oppression', (SELECT id FROM Killers WHERE killer_name = 'The Twins'), 'assets/img/killer/perks/oppression.png'),
('Overcharge', (SELECT id FROM Killers WHERE killer_name = 'The Doctor'), 'assets/img/killer/perks/overcharge.png'),
('Overwhelming Presence', (SELECT id FROM Killers WHERE killer_name = 'The Doctor'), 'assets/img/killer/perks/overwhelming_presence.png'),
('Play With Your Food', (SELECT id FROM Killers WHERE killer_name = 'The Shape'), 'assets/img/killer/perks/play_with_your_food.png'),
('Pop Goes the Weasel', (SELECT id FROM Killers WHERE killer_name = 'The Clown'), 'assets/img/killer/perks/pop_goes_the_weasel.png'),
('Predator', (SELECT id FROM Killers WHERE killer_name = 'The Wraith'), 'assets/img/killer/perks/predator.png'),
('Rancor', (SELECT id FROM Killers WHERE killer_name = 'The Spirit'), 'assets/img/killer/perks/rancor.png'),
('Rapid Brutality', (SELECT id FROM Killers WHERE killer_name = 'The Xenomorph'), 'assets/img/killer/perks/rapid_brutality.png'),
('Remember Me', (SELECT id FROM Killers WHERE killer_name = 'The Nightmare'), 'assets/img/killer/perks/remember_me.png'),
('Save the Best for Last', (SELECT id FROM Killers WHERE killer_name = 'The Shape'), 'assets/img/killer/perks/save_the_best_for_last.png'),
('Scourge Hook: Floods of Rage', (SELECT id FROM Killers WHERE killer_name = 'The Onryō'), 'assets/img/killer/perks/scourge_hook_floods_of_rage.png'),
('Scourge Hook: Gift of Pain', (SELECT id FROM Killers WHERE killer_name = 'The Artist'), 'assets/img/killer/perks/scourge_hook_gift_of_pain.png'),
('Scourge Hook: Pain Resonance', (SELECT id FROM Killers WHERE killer_name = 'The Cenobite'), 'assets/img/killer/perks/scourge_hook_pain_resonance.png'),
('Septic Touch', (SELECT id FROM Killers WHERE killer_name = 'The Dredge'), 'assets/img/killer/perks/septic_touch.png'),
('Shadowborn', (SELECT id FROM Killers WHERE killer_name = 'The Wraith'), 'assets/img/killer/perks/shadowborn.png'),
('Sloppy Butcher', NULL, 'assets/img/killer/perks/sloppy_butcher.png'),
('Spies from the Shadows', NULL, 'assets/img/killer/perks/spies_from_the_shadows.png'),
('Spirit Fury', (SELECT id FROM Killers WHERE killer_name = 'The Spirit'), 'assets/img/killer/perks/spirit_fury.png'),
('Starstruck', (SELECT id FROM Killers WHERE killer_name = 'The Trickster'), 'assets/img/killer/perks/starstruck.png'),
('Stridor', (SELECT id FROM Killers WHERE killer_name = 'The Nurse'), 'assets/img/killer/perks/stridor.png'),
('Superior Anatomy', (SELECT id FROM Killers WHERE killer_name = 'The Mastermind'), 'assets/img/killer/perks/superior_anatomy.png'),
('Surge', (SELECT id FROM Killers WHERE killer_name = 'The Demogorgon'), 'assets/img/killer/perks/surge.png'),
('Terminus', (SELECT id FROM Killers WHERE killer_name = 'The Mastermind'), 'assets/img/killer/perks/terminus.png'),
('Territorial Imperative', (SELECT id FROM Killers WHERE killer_name = 'The Huntress'), 'assets/img/killer/perks/territorial_imperative.png'),
('THWACK!', (SELECT id FROM Killers WHERE killer_name = 'The Skull Merchant'), 'assets/img/killer/perks/thwack.png'),
('Thrilling Tremors', (SELECT id FROM Killers WHERE killer_name = 'The Ghost Face'), 'assets/img/killer/perks/thrilling_tremors.png'),
('Tinkerer', (SELECT id FROM Killers WHERE killer_name = 'The Hillbilly'), 'assets/img/killer/perks/tinkerer.png'),
('Trail of Torment', (SELECT id FROM Killers WHERE killer_name = 'The Executioner'), 'assets/img/killer/perks/trail_of_torment.png'),
('Unbound', (SELECT id FROM Killers WHERE killer_name = 'The Xenomorph'), 'assets/img/killer/perks/unbound.png'),
('Unforeseen', (SELECT id FROM Killers WHERE killer_name = 'The Unknown'), 'assets/img/killer/perks/unforeseen.png'),
('Unrelenting', NULL, 'assets/img/killer/perks/unrelenting.png'),
('Weave Attunement', (SELECT id FROM Killers WHERE killer_name = 'The Lich'), 'assets/img/killer/perks/weave_attunement.png'),
('Whispers', NULL, 'assets/img/killer/perks/whispers.png'),
('Zanshin Tactics', (SELECT id FROM Killers WHERE killer_name = 'The Oni'), 'assets/img/killer/perks/zanshin_tactics.png');