INSERT INTO Killers (
    killer_name, name, gender, power, movement_speed, terror_radius, icon, bg
) VALUES
('The Trapper', 'Evan MacMillan', 'Male', 'Bear Trap', 4.6, 32, 'assets/img/killer/icon/trapper_icon.png', 'assets/img/killer/bg/trapper_bg.png'),
('The Wraith', 'Philip Ojomo', 'Male', 'Wailing Bell', 4.6, 32, 'assets/img/killer/icon/wraith_icon.png', 'assets/img/killer/bg/wraith_bg.png'),
('The Hillbilly', 'Max Thompson Jr.', 'Male', 'Chainsaw', 4.6, 32, 'assets/img/killer/icon/hillbilly_icon.png', 'assets/img/killer/bg/hillbilly_bg.png'),
('The Nurse', 'Sally Smithson', 'Female', 'Spencer’s Last Breath', 3.8, 32, 'assets/img/killer/icon/nurse_icon.png', 'assets/img/killer/bg/nurse_bg.png'),
('The Shape', 'Michael Myers', 'Male', 'Evil Within', 4.6, 6, 'assets/img/killer/icon/shape_icon.png', 'assets/img/killer/bg/shape_bg.png'),
('The Hag', 'Lisa Sherwood', 'Female', 'Blackened Catalyst', 4.4, 24, 'assets/img/killer/icon/hag_icon.png', 'assets/img/killer/bg/hag_bg.png'),
('The Doctor', 'Herman Carter', 'Male', 'Carter’s Spark', 4.6, 32, 'assets/img/killer/icon/doctor_icon.png', 'assets/img/killer/bg/doctor_bg.png'),
('The Huntress', 'Anna', 'Female', 'Hunting Hatchets', 4.4, 20, 'assets/img/killer/icon/huntress_icon.png', 'assets/img/killer/bg/huntress_bg.png'),
('The Cannibal', 'Bubba Sawyer', 'Male', 'Chainsaw Sweep', 4.6, 32, 'assets/img/killer/icon/cannibal_icon.png', 'assets/img/killer/bg/cannibal_bg.png'),
('The Nightmare', 'Freddy Krueger', 'Male', 'Dream Demon', 4.6, 32, 'assets/img/killer/icon/nightmare_icon.png', 'assets/img/killer/bg/nightmare_bg.png'),
('The Pig', 'Amanda Young', 'Female', 'Jigsaw’s Baptism', 4.6, 32, 'assets/img/killer/icon/pig_icon.png', 'assets/img/killer/bg/pig_bg.png'),
('The Clown', 'Jeffrey Hawk', 'Male', 'The Afterpiece Tonic', 4.6, 32, 'assets/img/killer/icon/clown_icon.png', 'assets/img/killer/bg/clown_bg.png'),
('The Spirit', 'Rin Yamaoka', 'Female', 'Yamaoka’s Haunting', 4.4, 24, 'assets/img/killer/icon/spirit_icon.png', 'assets/img/killer/bg/spirit_bg.png'),
('The Legion', 'Frank, Julie, Susie, Joey', 'Various', 'Feral Frenzy', 4.6, 32, 'assets/img/killer/icon/legion_icon.png', 'assets/img/killer/bg/legion_bg.png'),
('The Plague', 'Adiris', 'Female', 'Vile Purge', 4.6, 32, 'assets/img/killer/icon/plague_icon.png', 'assets/img/killer/bg/plague_bg.png'),
('The Ghost Face', 'Danny Johnson', 'Male', 'Night Shroud', 4.6, 32, 'assets/img/killer/icon/ghostface_icon.png', 'assets/img/killer/bg/ghostface_bg.png'),
('The Demogorgon', 'Demogorgon', 'Unknown', 'Of the Abyss', 4.6, 32, 'assets/img/killer/icon/demogorgon_icon.png', 'assets/img/killer/bg/demogorgon_bg.png'),
('The Oni', 'Kazan Yamaoka', 'Male', 'Yamaoka’s Wrath', 4.6, 32, 'assets/img/killer/icon/oni_icon.png', 'assets/img/killer/bg/oni_bg.png'),
('The Deathslinger', 'Caleb Quinn', 'Male', 'The Redeemer', 4.4, 24, 'assets/img/killer/icon/deathslinger_icon.png', 'assets/img/killer/bg/deathslinger_bg.png'),
('The Executioner', 'Pyramid Head', 'Male', 'Rites of Judgement', 4.6, 32, 'assets/img/killer/icon/executioner_icon.png', 'assets/img/killer/bg/executioner_bg.png'),
('The Blight', 'Talbot Grimes', 'Male', 'Blighted Corruption', 4.6, 32, 'assets/img/killer/icon/blight_icon.png', 'assets/img/killer/bg/blight_bg.png'),
('The Twins', 'Charlotte & Victor', 'Female/Male', 'Blood Bond', 4.4, 32, 'assets/img/killer/icon/twins_icon.png', 'assets/img/killer/bg/twins_bg.png'),
('The Trickster', 'Ji-Woon Hak', 'Male', 'Showstopper', 4.4, 24, 'assets/img/killer/icon/trickster_icon.png', 'assets/img/killer/bg/trickster_bg.png'),
('The Nemesis', 'Nemesis-T Type', 'Male', 'T-Virus', 4.6, 32, 'assets/img/killer/icon/nemesis_icon.png', 'assets/img/killer/bg/nemesis_bg.png'),
('The Cenobite', 'Pinhead', 'Male', 'Summons of Pain', 4.6, 32, 'assets/img/killer/icon/cenobite_icon.png', 'assets/img/killer/bg/cenobite_bg.png'),
('The Artist', 'Carmina Mora', 'Female', 'Birds of Torment', 4.4, 32, 'assets/img/killer/icon/artist_icon.png', 'assets/img/killer/bg/artist_bg.png'),
('The Onryō', 'Sadako Yamamura', 'Female', 'Deluge of Fear', 4.6, 32, 'assets/img/killer/icon/onryo_icon.png', 'assets/img/killer/bg/onryo_bg.png'),
('The Dredge', 'The Dredge', 'Unknown', 'Reign of Darkness', 4.6, 32, 'assets/img/killer/icon/dredge_icon.png', 'assets/img/killer/bg/dredge_bg.png'),
('The Mastermind', 'Albert Wesker', 'Male', 'Virulent Bound', 4.6, 32, 'assets/img/killer/icon/mastermind_icon.png', 'assets/img/killer/bg/mastermind_bg.png'),
('The Knight', 'Tarhos Kovács', 'Male', 'Guardia Compagnia', 4.6, 32, 'assets/img/killer/icon/knight_icon.png', 'assets/img/killer/bg/knight_bg.png'),
('The Skull Merchant', 'Adriana Imai', 'Female', 'Eyes in the Sky', 4.6, 32, 'assets/img/killer/icon/skull_icon.png', 'assets/img/killer/bg/skull_bg.png'),
('The Singularity', 'Hux-A7-13', 'Unknown', 'Quantum Instantiation', 4.4, 32, 'assets/img/killer/icon/singularity_icon.png', 'assets/img/killer/bg/singularity_bg.png'),
('The Xenomorph', 'Xenomorph', 'Unknown', 'Hidden Pursuit', 4.6, 32, 'assets/img/killer/icon/xenomorph_icon.png', 'assets/img/killer/bg/xenomorph_bg.png'),
('The Good Guy', 'Chucky', 'Male', 'Playtimes Over', 4.4, 32, 'assets/img/killer/icon/chucky_icon.png', 'assets/img/killer/bg/chucky_bg.png'),
('The Unknown', 'The Unknown', 'Unknown', 'UVX', 4.6, 32, 'assets/img/killer/icon/unknown_icon.png', 'assets/img/killer/bg/unknown_bg.png'),
('The Lich', 'Vecna', 'Male', 'Vile Darkness', 4.6, 32, 'assets/img/killer/icon/vecna_icon.png', 'assets/img/killer/bg/vecna_bg.png'),
('The Dark Lord', 'Dracula', 'Male', 'Vampiric Shift', 4.6, 32, 'assets/img/killer/icon/dracula_icon.png', 'assets/img/killer/bg/dracula_bg.png'),
('The Houndmaster', 'Portia Maye', 'Female', 'Scent of Blood', 4.6, 32, 'assets/img/killer/icon/hound_icon.png', 'assets/img/killer/bg/hound_bg.png'),
('The Ghoul', 'Ken Kaneki', 'Male', 'One-Eyed Terror', 4.6, 32, 'assets/img/killer/icon/ghoul_icon.png', 'assets/img/killer/bg/ghoul_bg.png'),
('The Animatronic', 'William Afton', 'Male', 'Fazbears Fright', 4.6, 32, 'assets/img/killer/icon/afton_icon.png', 'assets/img/killer/bg/afton_bg.png');