INSERT INTO Survivor_Perks (name, survivor_id, icon) VALUES
('Ace in the Hole', (SELECT id FROM Survivors WHERE name = 'Ace Visconti'), 'assets/img/survivor/perks/ace_in_the_hole.png'),
('Adrenaline', (SELECT id FROM Survivors WHERE name = 'Meg Thomas'), 'assets/img/survivor/perks/adrenaline.png'),
('Aftercare', (SELECT id FROM Survivors WHERE name = 'Jeff Johansen'), 'assets/img/survivor/perks/aftercare.png'),
('Alert', (SELECT id FROM Survivors WHERE name = 'Feng Min'), 'assets/img/survivor/perks/alert.png'),
('Any Means Necessary', (SELECT id FROM Survivors WHERE name = 'Yui Kimura'), 'assets/img/survivor/perks/any_means_necessary.png'),
('Appraisal', (SELECT id FROM Survivors WHERE name = 'Élodie Rakoto'), 'assets/img/survivor/perks/appraisal.png'),
('Autodidact', (SELECT id FROM Survivors WHERE name = 'Adam Francis'), 'assets/img/survivor/perks/autodidact.png'),
('Babysitter', (SELECT id FROM Survivors WHERE name = 'Steve Harrington'), 'assets/img/survivor/perks/babysitter.png'),
('Background Player', (SELECT id FROM Survivors WHERE name = 'Renato Lyra'), 'assets/img/survivor/perks/background_player.png'),
('Balanced Landing', (SELECT id FROM Survivors WHERE name = 'Nea Karlsson'), 'assets/img/survivor/perks/balanced_landing.png'),
('Bardic Inspiration', (SELECT id FROM Survivors WHERE name = 'Aestri Yazar & Baermar Uraz'), 'assets/img/survivor/perks/bardic_inspiration.png'),
('Better Than New', (SELECT id FROM Survivors WHERE name = 'Rebecca Chambers'), 'assets/img/survivor/perks/better_than_new.png'),
('Bite the Bullet', (SELECT id FROM Survivors WHERE name = 'Leon Scott Kennedy'), 'assets/img/survivor/perks/bite_the_bullet.png'),
('Blast Mine', (SELECT id FROM Survivors WHERE name = 'Jill Valentine'), 'assets/img/survivor/perks/blast_mine.png'),
('Blood Rush', (SELECT id FROM Survivors WHERE name = 'Renato Lyra'), 'assets/img/survivor/perks/blood_rush.png'),
('Boil Over', (SELECT id FROM Survivors WHERE name = 'David King'), 'assets/img/survivor/perks/boil_over.png'),
('Boon: Circle of Healing', (SELECT id FROM Survivors WHERE name = 'Mikaela Reid'), 'assets/img/survivor/perks/boon_circle_of_healing.png'),
('Boon: Dark Theory', (SELECT id FROM Survivors WHERE name = 'Yoichi Asakawa'), 'assets/img/survivor/perks/boon_dark_theory.png'),
('Boon: Exponential', (SELECT id FROM Survivors WHERE name = 'Jonah Vasquez'), 'assets/img/survivor/perks/boon_exponential.png'),
('Boon: Illumination', (SELECT id FROM Survivors WHERE name = 'Alan Wake'), 'assets/img/survivor/perks/boon_illumination.png'),
('Boon: Shadow Step', (SELECT id FROM Survivors WHERE name = 'Mikaela Reid'), 'assets/img/survivor/perks/boon_shadow_step.png'),
('Botany Knowledge', (SELECT id FROM Survivors WHERE name = 'Claudette Morel'), 'assets/img/survivor/perks/botany_knowledge.png'),
('Breakdown', (SELECT id FROM Survivors WHERE name = 'Jeff Johansen'), 'assets/img/survivor/perks/breakdown.png'),
('Buckle Up', (SELECT id FROM Survivors WHERE name = 'Ash Williams'), 'assets/img/survivor/perks/buckle_up.png'),
('Built to Last', (SELECT id FROM Survivors WHERE name = 'Felix Richter'), 'assets/img/survivor/perks/built_to_last.png'),
('Camaraderie', (SELECT id FROM Survivors WHERE name = 'Steve Harrington'), 'assets/img/survivor/perks/camaraderie.png'),
('Champion of Light', (SELECT id FROM Survivors WHERE name = 'Alan Wake'), 'assets/img/survivor/perks/champion_of_light.png'),
('Chemical Trap', (SELECT id FROM Survivors WHERE name = 'Jill Valentine'), 'assets/img/survivor/perks/chemical_trap.png'),
('Clairvoyance', (SELECT id FROM Survivors WHERE name = 'Mikaela Reid'), 'assets/img/survivor/perks/clairvoyance.png'),
('Corrective Action', (SELECT id FROM Survivors WHERE name = 'Jonah Vasquez'), 'assets/img/survivor/perks/corrective_action.png'),
('Counterforce', (SELECT id FROM Survivors WHERE name = 'Jill Valentine'), 'assets/img/survivor/perks/counterforce.png'),
('Cut Loose', (SELECT id FROM Survivors WHERE name = 'Thalita Lyra'), 'assets/img/survivor/perks/cut_loose.png'),
('Dark Sense', NULL, 'assets/img/survivor/perks/dark_sense.png'),
('Dead Hard', (SELECT id FROM Survivors WHERE name = 'David King'), 'assets/img/survivor/perks/dead_hard.png'),
('Deadline', (SELECT id FROM Survivors WHERE name = 'Alan Wake'), 'assets/img/survivor/perks/deadline.png'),
('Decisive Strike', (SELECT id FROM Survivors WHERE name = 'Laurie Strode'), 'assets/img/survivor/perks/decisive_strike.png'),
('Deja Vu', NULL, 'assets/img/survivor/perks/deja_vu.png'),
('Deliverance', (SELECT id FROM Survivors WHERE name = 'Adam Francis' ), 'assets/img/survivor/perks/deliverance.png'),
('Desperate Measures', (SELECT id FROM Survivors WHERE name = 'Felix Richter'), 'assets/img/survivor/perks/desperate_measures.png'),
('Distortion', (SELECT id FROM Survivors WHERE name = 'Jeff Johansen'), 'assets/img/survivor/perks/distortion.png'),
('Diversion', (SELECT id FROM Survivors WHERE name = 'Adam Francis'), 'assets/img/survivor/perks/diversion.png'),
('Dramaturgy', (SELECT id FROM Survivors WHERE name = 'Nicolas Cage'), 'assets/img/survivor/perks/dramaturgy.png'),
('Empathy', (SELECT id FROM Survivors WHERE name = 'Claudette Morel'), 'assets/img/survivor/perks/empathy.png'),
('Fast Track', (SELECT id FROM Survivors WHERE name = 'Yun‑Jin Lee'), 'assets/img/survivor/perks/fast_track.png'),
('Finesse', (SELECT id FROM Survivors WHERE name = 'Lara Croft'), 'assets/img/survivor/perks/finesse.png'),
('Fixated', (SELECT id FROM Survivors WHERE name = 'Nancy Wheeler'), 'assets/img/survivor/perks/fixated.png'),
('Flashbang', (SELECT id FROM Survivors WHERE name = 'Leon Scott Kennedy'), 'assets/img/survivor/perks/flashbang.png'),
('Flip‑Flop', (SELECT id FROM Survivors WHERE name = 'Ash Williams'), 'assets/img/survivor/perks/flip_flop.png'),
('Fogwise', (SELECT id FROM Survivors WHERE name = 'Vittorio Toscano'), 'assets/img/survivor/perks/fogwise.png'),
('For the People', (SELECT id FROM Survivors WHERE name = 'Zarina Kassir'), 'assets/img/survivor/perks/for_the_people.png'),
('Friendly Competition', (SELECT id FROM Survivors WHERE name = 'Thalita Lyra'), 'assets/img/survivor/perks/friendly_competition.png'),
('Hardened', (SELECT id FROM Survivors WHERE name = 'Lara Croft'), 'assets/img/survivor/perks/hardened.png'),
('Head On', (SELECT id FROM Survivors WHERE name = 'Jane Romero'), 'assets/img/survivor/perks/head_on.png'),
('Hope', NULL, 'assets/img/survivor/perks/hope.png'),
('Hyperfocus', (SELECT id FROM Survivors WHERE name = 'Rebecca Chambers'), 'assets/img/survivor/perks/hyperfocus.png'),
('Inner Focus', (SELECT id FROM Survivors WHERE name = 'Haddie Kaur'), 'assets/img/survivor/perks/inner_focus.png'),
('Inner Healing', (SELECT id FROM Survivors WHERE name = 'Nancy Wheeler'), 'assets/img/survivor/perks/inner_healing.png'),
('Invocation: Weaving Spiders', (SELECT id FROM Survivors WHERE name = 'Sable Ward'), 'assets/img/survivor/perks/invocation_weaving_spiders.png'),
('Iron Will', (SELECT id FROM Survivors WHERE name = 'Jake Park'), 'assets/img/survivor/perks/iron_will.png'),
('Kindred', NULL, 'assets/img/survivor/perks/kindred.png'),
('Leader', (SELECT id FROM Survivors WHERE name = 'Dwight Fairfield'), 'assets/img/survivor/perks/leader.png'),
('Left Behind', (SELECT id FROM Survivors WHERE name = 'Bill Overbeck'), 'assets/img/survivor/perks/left_behind.png'),
('Light-footed', (SELECT id FROM Survivors WHERE name = 'Ellen Ripley'), 'assets/img/survivor/perks/light_footed.png'),
('Lightweight', NULL, 'assets/img/survivor/perks/lightweight.png'),
('Lithe', (SELECT id FROM Survivors WHERE name = 'Feng Min'), 'assets/img/survivor/perks/lithe.png'),
('Low Profile', (SELECT id FROM Survivors WHERE name = 'Ada Wong'), 'assets/img/survivor/perks/low_profile.png'),
('Lucky Break', (SELECT id FROM Survivors WHERE name = 'Yui Kimura'), 'assets/img/survivor/perks/lucky_break.png'),
('Lucky Star', (SELECT id FROM Survivors WHERE name = 'Lara Croft'), 'assets/img/survivor/perks/lucky_star.png'),
('Made for This', (SELECT id FROM Survivors WHERE name = 'Gabriel Soma'), 'assets/img/survivor/perks/made_for_this.png'),
('Mettle of Man', (SELECT id FROM Survivors WHERE name = 'Ash Williams'), 'assets/img/survivor/perks/mettle_of_man.png'),
('Mirrored Illusion', (SELECT id FROM Survivors WHERE name = 'Aestri Yazar & Baermar Uraz'), 'assets/img/survivor/perks/mirrored_illusion.png'),
('No One Left Behind', NULL, 'assets/img/survivor/perks/no_one_left_behind.png'),
('Object of Obsession', (SELECT id FROM Survivors WHERE name = 'Laurie Strode'), 'assets/img/survivor/perks/object_of_obsession.png'),
('Off the Record', (SELECT id FROM Survivors WHERE name = 'Zarina Kassir'), 'assets/img/survivor/perks/off_the_record.png'),
('Open-Handed', (SELECT id FROM Survivors WHERE name = 'Ace Visconti'), 'assets/img/survivor/perks/open_handed.png'),
('Overcome', (SELECT id FROM Survivors WHERE name = 'Jonah Vasquez'), 'assets/img/survivor/perks/overcome.png'),
('Overzealous', (SELECT id FROM Survivors WHERE name = 'Haddie Kaur'), 'assets/img/survivor/perks/overzealous.png'),
('Parental Guidance', (SELECT id FROM Survivors WHERE name = 'Cheryl Mason'), 'assets/img/survivor/perks/parental_guidance.png'),
('Plunderer’s Instinct', NULL, 'assets/img/survivor/perks/plunderers_instinct.png'),
('Plot Twist', (SELECT id FROM Survivors WHERE name = 'Nicolas Cage'), 'assets/img/survivor/perks/plot_twist.png'),
('Poised', (SELECT id FROM Survivors WHERE name = 'Jane Romero'), 'assets/img/survivor/perks/poised.png'),
('Potential Energy', (SELECT id FROM Survivors WHERE name = 'Vittorio Toscano'), 'assets/img/survivor/perks/potential_energy.png'),
('Power Struggle', (SELECT id FROM Survivors WHERE name = 'Élodie Rakoto'), 'assets/img/survivor/perks/power_struggle.png'),
('Premonition', NULL, 'assets/img/survivor/perks/premonition.png'),
('Prove Thyself', (SELECT id FROM Survivors WHERE name = 'Dwight Fairfield'), 'assets/img/survivor/perks/prove_thyself.png'),
('Quick & Quiet', (SELECT id FROM Survivors WHERE name = 'Meg Thomas'), 'assets/img/survivor/perks/quick_and_quiet.png'),
('Reactive Healing', (SELECT id FROM Survivors WHERE name = 'Ada Wong'), 'assets/img/survivor/perks/reactive_healing.png'),
('Red Herring', (SELECT id FROM Survivors WHERE name = 'Zarina Kassir'), 'assets/img/survivor/perks/red_herring.png'),
('Repressed Alliance', (SELECT id FROM Survivors WHERE name = 'Cheryl Mason'), 'assets/img/survivor/perks/repressed_alliance.png'),
('Residual Manifest', (SELECT id FROM Survivors WHERE name = 'Haddie Kaur'), 'assets/img/survivor/perks/residual_manifest.png'),
('Resilience', NULL, 'assets/img/survivor/perks/resilience.png'),
('Resurgence', (SELECT id FROM Survivors WHERE name = 'Rebecca Chambers'), 'assets/img/survivor/perks/resurgence.png'),
('Rookie Spirit', (SELECT id FROM Survivors WHERE name = 'Leon Scott Kennedy'), 'assets/img/survivor/perks/rookie_spirit.png'),
('Saboteur', (SELECT id FROM Survivors WHERE name = 'Jake Park'), 'assets/img/survivor/perks/saboteur.png'),
('Scene Partner', (SELECT id FROM Survivors WHERE name = 'Nicolas Cage'), 'assets/img/survivor/perks/scene_partner.png'),
('Second Wind', (SELECT id FROM Survivors WHERE name = 'Steve Harrington'), 'assets/img/survivor/perks/second_wind.png'),
('Self-Care', (SELECT id FROM Survivors WHERE name = 'Claudette Morel'), 'assets/img/survivor/perks/self_care.png'),
('Self-Preservation', (SELECT id FROM Survivors WHERE name = 'Yun‑Jin Lee'), 'assets/img/survivor/perks/self_preservation.png'),
('Slippery Meat', NULL, 'assets/img/survivor/perks/slippery_meat.png'),
('Small Game', NULL, 'assets/img/survivor/perks/small_game.png'),
('Smash Hit', (SELECT id FROM Survivors WHERE name = 'Yun‑Jin Lee'), 'assets/img/survivor/perks/smash_hit.png'),
('Solidarity', (SELECT id FROM Survivors WHERE name = 'Jane Romero'), 'assets/img/survivor/perks/solidarity.png'),
('Soul Guard', (SELECT id FROM Survivors WHERE name = 'Cheryl Mason'), 'assets/img/survivor/perks/soul_guard.png'),
('Specialist', (SELECT id FROM Survivors WHERE name = 'Lara Croft'), 'assets/img/survivor/perks/specialist.png'),
('Spine Chill', NULL, 'assets/img/survivor/perks/spine_chill.png'),
('Sprint Burst', (SELECT id FROM Survivors WHERE name = 'Meg Thomas'), 'assets/img/survivor/perks/sprint_burst.png'),
('Still Sight', (SELECT id FROM Survivors WHERE name = 'Aestri Yazar & Baermar Uraz'), 'assets/img/survivor/perks/still_sight.png'),
('Strength in Shadows', (SELECT id FROM Survivors WHERE name = 'Sable Ward'), 'assets/img/survivor/perks/strength_in_shadows.png'),
('Teamwork: Collective Stealth', (SELECT id FROM Survivors WHERE name = 'Thalita Lyra'), 'assets/img/survivor/perks/teamwork_collective_stealth.png'),
('Teamwork: Power of Two', (SELECT id FROM Survivors WHERE name = 'Renato Lyra'), 'assets/img/survivor/perks/teamwork_power_of_two.png'),
('Tenacity', (SELECT id FROM Survivors WHERE name = 'David Tapp'), 'assets/img/survivor/perks/tenacity.png'),
('This Is Not Happening', NULL, 'assets/img/survivor/perks/this_is_not_happening.png'),
('Troubleshooter', (SELECT id FROM Survivors WHERE name = 'Gabriel Soma'), 'assets/img/survivor/perks/troubleshooter.png'),
('Unbreakable', (SELECT id FROM Survivors WHERE name = 'Bill Overbeck'), 'assets/img/survivor/perks/unbreakable.png'),
('Up the Ante', (SELECT id FROM Survivors WHERE name = 'Ace Visconti'), 'assets/img/survivor/perks/up_the_ante.png'),
('Urban Evasion', (SELECT id FROM Survivors WHERE name = 'Nea Karlsson'), 'assets/img/survivor/perks/urban_evasion.png'),
('Vigil', (SELECT id FROM Survivors WHERE name = 'Quentin Smith'), 'assets/img/survivor/perks/vigil.png'),
('Visionary', (SELECT id FROM Survivors WHERE name = 'Felix Richter'), 'assets/img/survivor/perks/visionary.png'),
('Wake Up!', (SELECT id FROM Survivors WHERE name = 'Quentin Smith'), 'assets/img/survivor/perks/wake_up.png'),
('We’re Gonna Live Forever', (SELECT id FROM Survivors WHERE name = 'David King'), 'assets/img/survivor/perks/were_gonna_live_forever.png'),
('Weave Walker', (SELECT id FROM Survivors WHERE name = 'Taurie Cain'), 'assets/img/survivor/perks/weave_walker.png'),
('Wicked', (SELECT id FROM Survivors WHERE name = 'Sable Ward'), 'assets/img/survivor/perks/wicked.png'),
('Windows of Opportunity', (SELECT id FROM Survivors WHERE name = 'Kate Denson'), 'assets/img/survivor/perks/windows_of_opportunity.png'),
('Wiretap', (SELECT id FROM Survivors WHERE name = 'Ada Wong'), 'assets/img/survivor/perks/wiretap.png');