INSERT INTO Survivors (
    name, gender, icon, bg
) VALUES
('Dwight Fairfield', 'Male', 'assets/img/survivor/icon/dwight_icon.png', 'assets/img/survivor/bg/dwight_bg.jpg'),
('Meg Thomas', 'Female', 'assets/img/survivor/icon/meg_icon.png', 'assets/img/survivor/bg/meg_bg.jpg'),
('Claudette Morel', 'Female', 'assets/img/survivor/icon/claudette_icon.png', 'assets/img/survivor/bg/claudette_bg.jpg'),
('Jake Park', 'Male', 'assets/img/survivor/icon/jake_icon.png', 'assets/img/survivor/bg/jake_bg.jpg'),
('Nea Karlsson', 'Female', 'assets/img/survivor/icon/nea_icon.png', 'assets/img/survivor/bg/nea_bg.jpg'),
('Laurie Strode', 'Female', 'assets/img/survivor/icon/laurie_icon.png', 'assets/img/survivor/bg/laurie_bg.jpg'),
('Ace Visconti', 'Male', 'assets/img/survivor/icon/ace_icon.png', 'assets/img/survivor/bg/ace_bg.jpg'),
('Bill Overbeck', 'Male', 'assets/img/survivor/icon/bill_icon.png', 'assets/img/survivor/bg/bill_bg.jpg'),
('Feng Min', 'Female', 'assets/img/survivor/icon/feng_icon.png', 'assets/img/survivor/bg/feng_bg.jpg'),
('David King', 'Male', 'assets/img/survivor/icon/david_icon.png', 'assets/img/survivor/bg/david_bg.jpg'),
('Quentin Smith', 'Male', 'assets/img/survivor/icon/quentin_icon.png', 'assets/img/survivor/bg/quentin_bg.jpg'),
('David Tapp', 'Male', 'assets/img/survivor/icon/tapp_icon.png', 'assets/img/survivor/bg/tapp_bg.jpg'),
('Kate Denson', 'Female', 'assets/img/survivor/icon/kate_icon.png', 'assets/img/survivor/bg/kate_bg.jpg'),
('Adam Francis', 'Male', 'assets/img/survivor/icon/adam_icon.png', 'assets/img/survivor/bg/adam_bg.jpg'),
('Jeff Johansen', 'Male', 'assets/img/survivor/icon/jeff_icon.png', 'assets/img/survivor/bg/jeff_bg.jpg'),
('Jane Romero', 'Female', 'assets/img/survivor/icon/jane_icon.png', 'assets/img/survivor/bg/jane_bg.jpg'),
('Ash Williams', 'Male', 'assets/img/survivor/icon/ash_icon.png', 'assets/img/survivor/bg/ash_bg.jpg'),
('Nancy Wheeler', 'Female', 'assets/img/survivor/icon/nancy_icon.png', 'assets/img/survivor/bg/nancy_bg.jpg'),
('Steve Harrington', 'Male', 'assets/img/survivor/icon/steve_icon.png', 'assets/img/survivor/bg/steve_bg.jpg'),
('Yui Kimura', 'Female', 'assets/img/survivor/icon/yui_icon.png', 'assets/img/survivor/bg/yui_bg.jpg'),
('Zarina Kassir', 'Female', 'assets/img/survivor/icon/zarina_icon.png', 'assets/img/survivor/bg/zarina_bg.jpg'),
('Cheryl Mason', 'Female', 'assets/img/survivor/icon/cheryl_icon.png', 'assets/img/survivor/bg/cheryl_bg.jpg'),
('Felix Richter', 'Male', 'assets/img/survivor/icon/felix_icon.png', 'assets/img/survivor/bg/felix_bg.jpg'),
('Élodie Rakoto', 'Female', 'assets/img/survivor/icon/elodie_icon.png', 'assets/img/survivor/bg/elodie_bg.jpg'),
('Yun‑Jin Lee', 'Female', 'assets/img/survivor/icon/yunjin_icon.png', 'assets/img/survivor/bg/yunjin_bg.jpg'),
('Jill Valentine', 'Female', 'assets/img/survivor/icon/jill_icon.png', 'assets/img/survivor/bg/jill_bg.jpg'),
('Leon Scott Kennedy', 'Male', 'assets/img/survivor/icon/leon_icon.png', 'assets/img/survivor/bg/leon_bg.jpg'),
('Mikaela Reid', 'Female', 'assets/img/survivor/icon/mikaela_icon.png', 'assets/img/survivor/bg/mikaela_bg.jpg'),
('Jonah Vasquez', 'Male', 'assets/img/survivor/icon/jonah_icon.png', 'assets/img/survivor/bg/jonah_bg.jpg'),
('Yoichi Asakawa', 'Male', 'assets/img/survivor/icon/yoichi_icon.png', 'assets/img/survivor/bg/yoichi_bg.jpg'),
('Haddie Kaur', 'Female', 'assets/img/survivor/icon/haddie_icon.png', 'assets/img/survivor/bg/haddie_bg.jpg'),
('Ada Wong', 'Female', 'assets/img/survivor/icon/ada_icon.png', 'assets/img/survivor/bg/ada_bg.jpg'),
('Rebecca Chambers', 'Female', 'assets/img/survivor/icon/rebecca_icon.png', 'assets/img/survivor/bg/rebecca_bg.jpg'),
('Vittorio Toscano', 'Male', 'assets/img/survivor/icon/vittorio_icon.png', 'assets/img/survivor/bg/vittorio_bg.jpg'),
('Thalita Lyra', 'Female', 'assets/img/survivor/icon/thalita_icon.png', 'assets/img/survivor/bg/thalita_bg.jpg'),
('Renato Lyra', 'Male', 'assets/img/survivor/icon/renato_icon.png', 'assets/img/survivor/bg/renato_bg.jpg'),
('Gabriel Soma', 'Male', 'assets/img/survivor/icon/gabriel_icon.png', 'assets/img/survivor/bg/gabriel_bg.jpg'),
('Nicolas Cage', 'Male', 'assets/img/survivor/icon/nicolas_icon.png', 'assets/img/survivor/bg/nicolas_bg.jpg'),
('Ellen Ripley', 'Female', 'assets/img/survivor/icon/ripley_icon.png', 'assets/img/survivor/bg/ripley_bg.jpg'),
('Alan Wake', 'Male', 'assets/img/survivor/icon/alan_icon.png', 'assets/img/survivor/bg/alan_bg.jpg'),
('Sable Ward', 'Female', 'assets/img/survivor/icon/sable_icon.png', 'assets/img/survivor/bg/sable_bg.jpg'),
('Aestri Yazar & Baermar Uraz', 'Female/Male', 'assets/img/survivor/icon/aestri_icon.png', 'assets/img/survivor/bg/aestri_bg.jpg'),
('Lara Croft', 'Female', 'assets/img/survivor/icon/lara_icon.png', 'assets/img/survivor/bg/lara_bg.jpg'),
('Trevor Belmont', 'Male', 'assets/img/survivor/icon/trevor_icon.png', 'assets/img/survivor/bg/trevor_bg.jpg'),
('Taurie Cain', 'Female', 'assets/img/survivor/icon/taurie_icon.png', 'assets/img/survivor/bg/taurie_bg.jpg');
