INSERT INTO Items (category_id, name, rarity_id, icon) VALUES
(1, 'Flashlight', 2, 'assets/img/survivor/item/flashlight.png'),
(1, 'Sport Flashlight', 3, 'assets/img/survivor/item/sport_flashlight.png'),
(1, 'Utility Flashlight', 4, 'assets/img/survivor/item/utility_flashlight.png'),
(2, 'Camping Aid Kit', 1, 'assets/img/survivor/item/camping_aid_kit.png'),
(2, 'First Aid Kit', 2, 'assets/img/survivor/item/first_aid_kit.png'),
(2, 'Emergency Med-Kit', 3, 'assets/img/survivor/item/emergency_med_kit.png'),
(2, 'Ranger Med-Kit', 4, 'assets/img/survivor/item/ranger_med_kit.png'),
(3, 'Worn-Out Tools', 1, 'assets/img/survivor/item/worn_out_tools.png'),
(3, 'Toolbox', 2, 'assets/img/survivor/item/toolbox.png'),
(3, 'Mechanic’s Toolbox', 3, 'assets/img/survivor/item/mechanics_toolbox.png'),
(3, 'Commodious Toolbox', 3, 'assets/img/survivor/item/commodious_toolbox.png'),
(3, 'Engineer’s Toolbox', 4, 'assets/img/survivor/item/engineers_toolbox.png'),
(3, 'Alex’s Toolbox', 4, 'assets/img/survivor/item/alexs_toolbox.png'),
(4, 'Broken Key', 3, 'assets/img/survivor/item/broken_key.png'),
(4, 'Dull Key', 4, 'assets/img/survivor/item/dull_key.png'),
(4, 'Skeleton Key', 5, 'assets/img/survivor/item/skeleton_key.png'),
(5, 'Map', 3, 'assets/img/survivor/item/map.png'),
(5, 'Rainbow Map', 5, 'assets/img/survivor/item/rainbow_map.png');