INSERT INTO Survivor_Perks (name, survivor_id, icon) VALUES
('Ace in the Hole', (SELECT id FROM Survivors WHERE name = 'Ace Visconti'), 'assets/img/survivor/perk/ace_in_the_hole.png'),
('Adrenaline', (SELECT id FROM Survivors WHERE name = 'Meg Thomas'), 'assets/img/survivor/perk/adrenaline.png'),
('Aftercare', (SELECT id FROM Survivors WHERE name = 'Jeff Johansen'), 'assets/img/survivor/perk/aftercare.png'),
('Alert', (SELECT id FROM Survivors WHERE name = 'Feng Min'), 'assets/img/survivor/perk/alert.png'),
('Any Means Necessary', (SELECT id FROM Survivors WHERE name = 'Yui Kimura'), 'assets/img/survivor/perk/any_means_necessary.png'),
('Appraisal', (SELECT id FROM Survivors WHERE name = 'Élodie Rakoto'), 'assets/img/survivor/perk/appraisal.png'),
('Autodidact', (SELECT id FROM Survivors WHERE name = 'Adam Francis'), 'assets/img/survivor/perk/autodidact.png'),
('Babysitter', (SELECT id FROM Survivors WHERE name = 'Steve Harrington'), 'assets/img/survivor/perk/babysitter.png'),
('Background Player', (SELECT id FROM Survivors WHERE name = 'Renato Lyra'), 'assets/img/survivor/perk/background_player.png'),
('Balanced Landing', (SELECT id FROM Survivors WHERE name = 'Nea Karlsson'), 'assets/img/survivor/perk/balanced_landing.png'),
('Bardic Inspiration', (SELECT id FROM Survivors WHERE name = 'Aestri Yazar & Baermar Uraz'), 'assets/img/survivor/perk/bardic_inspiration.png'),
('Better Together', (SELECT id FROM Survivors WHERE name = 'Nancy Wheeler'), 'assets/img/survivor/perk/better_together.png'),
('Better Than New', (SELECT id FROM Survivors WHERE name = 'Rebecca Chambers'), 'assets/img/survivor/perk/better_than_new.png'),
('Bite the Bullet', (SELECT id FROM Survivors WHERE name = 'Leon Scott Kennedy'), 'assets/img/survivor/perk/bite_the_bullet.png'),
('Blast Mine', (SELECT id FROM Survivors WHERE name = 'Jill Valentine'), 'assets/img/survivor/perk/blast_mine.png'),
('Blood Pact', (SELECT id FROM Survivors WHERE name = 'Cheryl Mason'), 'assets/img/survivor/perk/blood_pact.png'),
('Blood Rush', (SELECT id FROM Survivors WHERE name = 'Renato Lyra'), 'assets/img/survivor/perk/blood_rush.png'),
('Boil Over', (SELECT id FROM Survivors WHERE name = 'Kate Denson'), 'assets/img/survivor/perk/boil_over.png'),
('Bond', (SELECT id FROM Survivors WHERE name = 'Dwight Fairfield'), 'assets/img/survivor/perk/bond.png'),
('Boon: Circle of Healing', (SELECT id FROM Survivors WHERE name = 'Mikaela Reid'), 'assets/img/survivor/perk/boon_circle_of_healing.png'),
('Boon: Dark Theory', (SELECT id FROM Survivors WHERE name = 'Yoichi Asakawa'), 'assets/img/survivor/perk/boon_dark_theory.png'),
('Boon: Exponential', (SELECT id FROM Survivors WHERE name = 'Jonah Vasquez'), 'assets/img/survivor/perk/boon_exponential.png'),
('Boon: Illumination', (SELECT id FROM Survivors WHERE name = 'Alan Wake'), 'assets/img/survivor/perk/boon_illumination.png'),
('Boon: Shadow Step', (SELECT id FROM Survivors WHERE name = 'Mikaela Reid'), 'assets/img/survivor/perk/boon_shadow_step.png'),
('Borrowed Time', (SELECT id FROM Survivors WHERE name = 'Bill Overbeck'), 'assets/img/survivor/perk/borrowed_time.png'),
('Botany Knowledge', (SELECT id FROM Survivors WHERE name = 'Claudette Morel'), 'assets/img/survivor/perk/botany_knowledge.png'),
('Breakdown', (SELECT id FROM Survivors WHERE name = 'Jeff Johansen'), 'assets/img/survivor/perk/breakdown.png'),
('Breakout', (SELECT id FROM Survivors WHERE name = 'Yui Kimura'), 'assets/img/survivor/perk/breakout.png'),
('Buckle Up', (SELECT id FROM Survivors WHERE name = 'Ash Williams'), 'assets/img/survivor/perk/buckle_up.png'),
('Built to Last', (SELECT id FROM Survivors WHERE name = 'Felix Richter'), 'assets/img/survivor/perk/built_to_last.png'),
('Calm Spirit', (SELECT id FROM Survivors WHERE name = 'Jake Park'), 'assets/img/survivor/perk/calm_spirit.png'),
('Camaraderie', (SELECT id FROM Survivors WHERE name = 'Steve Harrington'), 'assets/img/survivor/perk/camaraderie.png'),
('Champion of Light', (SELECT id FROM Survivors WHERE name = 'Alan Wake'), 'assets/img/survivor/perk/champion_of_light.png'),
('Chemical Trap', (SELECT id FROM Survivors WHERE name = 'Ellen Ripley'), 'assets/img/survivor/perk/chemical_trap.png'),
('Clairvoyance', (SELECT id FROM Survivors WHERE name = 'Mikaela Reid'), 'assets/img/survivor/perk/clairvoyance.png'),
('Clean Break', (SELECT id FROM Survivors WHERE name = 'Taurie Cain'), 'assets/img/survivor/perk/clean_break.png'),
('Corrective Action', (SELECT id FROM Survivors WHERE name = 'Jonah Vasquez'), 'assets/img/survivor/perk/corrective_action.png'),
('Counterforce', (SELECT id FROM Survivors WHERE name = 'Jill Valentine'), 'assets/img/survivor/perk/counterforce.png'),
('Cut Loose', (SELECT id FROM Survivors WHERE name = 'Thalita Lyra'), 'assets/img/survivor/perk/cut_loose.png'),
('Dance With Me', (SELECT id FROM Survivors WHERE name = 'Kate Denson'), 'assets/img/survivor/perk/dance_with_me.png'),
('Dark Sense', NULL, 'assets/img/survivor/perk/dark_sense.png'),
('Dead Hard', (SELECT id FROM Survivors WHERE name = 'David King'), 'assets/img/survivor/perk/dead_hard.png'),
('Deadline', (SELECT id FROM Survivors WHERE name = 'Alan Wake'), 'assets/img/survivor/perk/deadline.png'),
('Deception', (SELECT id FROM Survivors WHERE name = 'Élodie Rakoto'), 'assets/img/survivor/perk/deception.png'),
('Decisive Strike', (SELECT id FROM Survivors WHERE name = 'Laurie Strode'), 'assets/img/survivor/perk/decisive_strike.png'),
('Deja Vu', NULL, 'assets/img/survivor/perk/deja_vu.png'),
('Deliverance', (SELECT id FROM Survivors WHERE name = 'Adam Francis' ), 'assets/img/survivor/perk/deliverance.png'),
('Desperate Measures', (SELECT id FROM Survivors WHERE name = 'Felix Richter'), 'assets/img/survivor/perk/desperate_measures.png'),
('Detective’s Hunch', (SELECT id FROM Survivors WHERE name = 'David Tapp'), 'assets/img/survivor/perk/detectives_hunch.png'),
('Distortion', (SELECT id FROM Survivors WHERE name = 'Jeff Johansen'), 'assets/img/survivor/perk/distortion.png'),
('Diversion', (SELECT id FROM Survivors WHERE name = 'Adam Francis'), 'assets/img/survivor/perk/diversion.png'),
('Dramaturgy', (SELECT id FROM Survivors WHERE name = 'Nicolas Cage'), 'assets/img/survivor/perk/dramaturgy.png'),
('Empathic Connection', (SELECT id FROM Survivors WHERE name = 'Yoichi Asakawa'), 'assets/img/survivor/perk/empathic_connection.png'),
('Empathy', (SELECT id FROM Survivors WHERE name = 'Claudette Morel'), 'assets/img/survivor/perk/empathy.png'),
('Exultation', (SELECT id FROM Survivors WHERE name = 'Trevor Belmont'), 'assets/img/survivor/perk/exultation.png'),
('Eyes of Belmont', (SELECT id FROM Survivors WHERE name = 'Trevor Belmont'), 'assets/img/survivor/perk/eyes_of_belmont.png'),
('Fast Track', (SELECT id FROM Survivors WHERE name = 'Yun‑Jin Lee'), 'assets/img/survivor/perk/fast_track.png'),
('Finesse', (SELECT id FROM Survivors WHERE name = 'Lara Croft'), 'assets/img/survivor/perk/finesse.png'),
('Fixated', (SELECT id FROM Survivors WHERE name = 'Nancy Wheeler'), 'assets/img/survivor/perk/fixated.png'),
('Flashbang', (SELECT id FROM Survivors WHERE name = 'Leon Scott Kennedy'), 'assets/img/survivor/perk/flashbang.png'),
('Flip‑Flop', (SELECT id FROM Survivors WHERE name = 'Ash Williams'), 'assets/img/survivor/perk/flip_flop.png'),
('Fogwise', (SELECT id FROM Survivors WHERE name = 'Vittorio Toscano'), 'assets/img/survivor/perk/fogwise.png'),
('For the People', (SELECT id FROM Survivors WHERE name = 'Zarina Kassir'), 'assets/img/survivor/perk/for_the_people.png'),
('Friendly Competition', (SELECT id FROM Survivors WHERE name = 'Thalita Lyra'), 'assets/img/survivor/perk/friendly_competition.png'),
('Hardened', (SELECT id FROM Survivors WHERE name = 'Lara Croft'), 'assets/img/survivor/perk/hardened.png'),
('Head On', (SELECT id FROM Survivors WHERE name = 'Jane Romero'), 'assets/img/survivor/perk/head_on.png'),
('Hope', NULL, 'assets/img/survivor/perk/hope.png'),
('Hyperfocus', (SELECT id FROM Survivors WHERE name = 'Rebecca Chambers'), 'assets/img/survivor/perk/hyperfocus.png'),
('Inner Focus', (SELECT id FROM Survivors WHERE name = 'Haddie Kaur'), 'assets/img/survivor/perk/inner_focus.png'),
('Inner Strength', (SELECT id FROM Survivors WHERE name = 'Nancy Wheeler'), 'assets/img/survivor/perk/inner_strength.png'),
('Invocation: Treacherous Crows', (SELECT id FROM Survivors WHERE name = 'Taurie Cain'), 'assets/img/survivor/perk/invocation_treacherous_crows.png'),
('Invocation: Weaving Spiders', (SELECT id FROM Survivors WHERE name = 'Sable Ward'), 'assets/img/survivor/perk/invocation_weaving_spiders.png'),
('Iron Will', (SELECT id FROM Survivors WHERE name = 'Jake Park'), 'assets/img/survivor/perk/iron_will.png'),
('Kindred', NULL, 'assets/img/survivor/perk/kindred.png'),
('Leader', (SELECT id FROM Survivors WHERE name = 'Dwight Fairfield'), 'assets/img/survivor/perk/leader.png'),
('Left Behind', (SELECT id FROM Survivors WHERE name = 'Bill Overbeck'), 'assets/img/survivor/perk/left_behind.png'),
('Light-footed', (SELECT id FROM Survivors WHERE name = 'Ellen Ripley'), 'assets/img/survivor/perk/light_footed.png'),
('Lightweight', NULL, 'assets/img/survivor/perk/lightweight.png'),
('Lithe', (SELECT id FROM Survivors WHERE name = 'Feng Min'), 'assets/img/survivor/perk/lithe.png'),
('Low Profile', (SELECT id FROM Survivors WHERE name = 'Ada Wong'), 'assets/img/survivor/perk/low_profile.png'),
('Lucky Break', (SELECT id FROM Survivors WHERE name = 'Yui Kimura'), 'assets/img/survivor/perk/lucky_break.png'),
('Lucky Star', (SELECT id FROM Survivors WHERE name = 'Ellen Ripley'), 'assets/img/survivor/perk/lucky_star.png'),
('Made for This', (SELECT id FROM Survivors WHERE name = 'Gabriel Soma'), 'assets/img/survivor/perk/made_for_this.png'),
('Mettle of Man', (SELECT id FROM Survivors WHERE name = 'Ash Williams'), 'assets/img/survivor/perk/mettle_of_man.png'),
('Mirrored Illusion', (SELECT id FROM Survivors WHERE name = 'Aestri Yazar & Baermar Uraz'), 'assets/img/survivor/perk/mirrored_illusion.png'),
('Moment of Glory', (SELECT id FROM Survivors WHERE name = 'Trevor Belmont'), 'assets/img/survivor/perk/moment_of_glory.png'),
('No Mither', (SELECT id FROM Survivors WHERE name = 'David King'), 'assets/img/survivor/perk/no_mither.png'),
('No One Left Behind', NULL, 'assets/img/survivor/perk/no_one_left_behind.png'),
('Object of Obsession', (SELECT id FROM Survivors WHERE name = 'Laurie Strode'), 'assets/img/survivor/perk/object_of_obsession.png'),
('Off the Record', (SELECT id FROM Survivors WHERE name = 'Zarina Kassir'), 'assets/img/survivor/perk/off_the_record.png'),
('Open-Handed', (SELECT id FROM Survivors WHERE name = 'Ace Visconti'), 'assets/img/survivor/perk/open_handed.png'),
('Overcome', (SELECT id FROM Survivors WHERE name = 'Jonah Vasquez'), 'assets/img/survivor/perk/overcome.png'),
('Overzealous', (SELECT id FROM Survivors WHERE name = 'Haddie Kaur'), 'assets/img/survivor/perk/overzealous.png'),
('Parental Guidance', (SELECT id FROM Survivors WHERE name = 'Yoichi Asakawa'), 'assets/img/survivor/perk/parental_guidance.png'),
('Pharmacy', (SELECT id FROM Survivors WHERE name = 'Quentin Smith'), 'assets/img/survivor/perk/pharmacy.png'),
('Plot Twist', (SELECT id FROM Survivors WHERE name = 'Nicolas Cage'), 'assets/img/survivor/perk/plot_twist.png'),
('Plunderer’s Instinct', NULL, 'assets/img/survivor/perk/plunderers_instinct.png'),
('Poised', (SELECT id FROM Survivors WHERE name = 'Jane Romero'), 'assets/img/survivor/perk/poised.png'),
('Potential Energy', (SELECT id FROM Survivors WHERE name = 'Vittorio Toscano'), 'assets/img/survivor/perk/potential_energy.png'),
('Power Struggle', (SELECT id FROM Survivors WHERE name = 'Élodie Rakoto'), 'assets/img/survivor/perk/power_struggle.png'),
('Premonition', NULL, 'assets/img/survivor/perk/premonition.png'),
('Prove Thyself', (SELECT id FROM Survivors WHERE name = 'Dwight Fairfield'), 'assets/img/survivor/perk/prove_thyself.png'),
('Quick & Quiet', (SELECT id FROM Survivors WHERE name = 'Meg Thomas'), 'assets/img/survivor/perk/quick_and_quiet.png'),
('Quick Gambit', (SELECT id FROM Survivors WHERE name = 'Vittorio Toscano'), 'assets/img/survivor/perk/quick_gambit.png'),
('Reactive Healing', (SELECT id FROM Survivors WHERE name = 'Ada Wong'), 'assets/img/survivor/perk/reactive_healing.png'),
('Reassurance', (SELECT id FROM Survivors WHERE name = 'Rebecca Chambers'), 'assets/img/survivor/perk/reassurance.png'),
('Red Herring', (SELECT id FROM Survivors WHERE name = 'Zarina Kassir'), 'assets/img/survivor/perk/red_herring.png'),
('Repressed Alliance', (SELECT id FROM Survivors WHERE name = 'Cheryl Mason'), 'assets/img/survivor/perk/repressed_alliance.png'),
('Residual Manifest', (SELECT id FROM Survivors WHERE name = 'Haddie Kaur'), 'assets/img/survivor/perk/residual_manifest.png'),
('Resilience', NULL, 'assets/img/survivor/perk/resilience.png'),
('Resurgence', (SELECT id FROM Survivors WHERE name = 'Jill Valentine'), 'assets/img/survivor/perk/resurgence.png'),
('Rookie Spirit', (SELECT id FROM Survivors WHERE name = 'Leon Scott Kennedy'), 'assets/img/survivor/perk/rookie_spirit.png'),
('Saboteur', (SELECT id FROM Survivors WHERE name = 'Jake Park'), 'assets/img/survivor/perk/saboteur.png'),
('Scavenger', (SELECT id FROM Survivors WHERE name = 'Gabriel Soma'), 'assets/img/survivor/perk/scavenger.png'),
('Scene Partner', (SELECT id FROM Survivors WHERE name = 'Nicolas Cage'), 'assets/img/survivor/perk/scene_partner.png'),
('Second Wind', (SELECT id FROM Survivors WHERE name = 'Steve Harrington'), 'assets/img/survivor/perk/second_wind.png'),
('Self-Care', (SELECT id FROM Survivors WHERE name = 'Claudette Morel'), 'assets/img/survivor/perk/self_care.png'),
('Self-Preservation', (SELECT id FROM Survivors WHERE name = 'Yun‑Jin Lee'), 'assets/img/survivor/perk/self_preservation.png'),
('Shoulder the Burden', (SELECT id FROM Survivors WHERE name = 'Taurie Cain'), 'assets/img/survivor/perk/shoulder_the_burden.png'),
('Slippery Meat', NULL, 'assets/img/survivor/perk/slippery_meat.png'),
('Small Game', NULL, 'assets/img/survivor/perk/small_game.png'),
('Smash Hit', (SELECT id FROM Survivors WHERE name = 'Yun‑Jin Lee'), 'assets/img/survivor/perk/smash_hit.png'),
('Sole Survivor', (SELECT id FROM Survivors WHERE name = 'Laurie Strode'), 'assets/img/survivor/perk/sole_survivor.png'),
('Solidarity', (SELECT id FROM Survivors WHERE name = 'Jane Romero'), 'assets/img/survivor/perk/solidarity.png'),
('Soul Guard', (SELECT id FROM Survivors WHERE name = 'Cheryl Mason'), 'assets/img/survivor/perk/soul_guard.png'),
('Specialist', (SELECT id FROM Survivors WHERE name = 'Lara Croft'), 'assets/img/survivor/perk/specialist.png'),
('Spine Chill', NULL, 'assets/img/survivor/perk/spine_chill.png'),
('Sprint Burst', (SELECT id FROM Survivors WHERE name = 'Meg Thomas'), 'assets/img/survivor/perk/sprint_burst.png'),
('Stake Out', (SELECT id FROM Survivors WHERE name = 'David Tapp'), 'assets/img/survivor/perk/stake_out.png'),
('Still Sight', (SELECT id FROM Survivors WHERE name = 'Aestri Yazar & Baermar Uraz'), 'assets/img/survivor/perk/still_sight.png'),
('Streetwise', (SELECT id FROM Survivors WHERE name = 'Nea Karlsson'), 'assets/img/survivor/perk/streetwise.png'),
('Strength in Shadows', (SELECT id FROM Survivors WHERE name = 'Sable Ward'), 'assets/img/survivor/perk/strength_in_shadows.png'),
('Teamwork: Collective Stealth', (SELECT id FROM Survivors WHERE name = 'Renato Lyra'), 'assets/img/survivor/perk/teamwork_collective_stealth.png'),
('Teamwork: Power of Two', (SELECT id FROM Survivors WHERE name = 'Thalita Lyra'), 'assets/img/survivor/perk/teamwork_power_of_two.png'),
('Technician', (SELECT id FROM Survivors WHERE name = 'Feng Min'), 'assets/img/survivor/perk/technician.png'),
('Tenacity', (SELECT id FROM Survivors WHERE name = 'David Tapp'), 'assets/img/survivor/perk/tenacity.png'),
('This Is Not Happening', NULL, 'assets/img/survivor/perk/this_is_not_happening.png'),
('Troubleshooter', (SELECT id FROM Survivors WHERE name = 'Gabriel Soma'), 'assets/img/survivor/perk/troubleshooter.png'),
('Unbreakable', (SELECT id FROM Survivors WHERE name = 'Bill Overbeck'), 'assets/img/survivor/perk/unbreakable.png'),
('Up the Ante', (SELECT id FROM Survivors WHERE name = 'Ace Visconti'), 'assets/img/survivor/perk/up_the_ante.png'),
('Urban Evasion', (SELECT id FROM Survivors WHERE name = 'Nea Karlsson'), 'assets/img/survivor/perk/urban_evasion.png'),
('Vigil', (SELECT id FROM Survivors WHERE name = 'Quentin Smith'), 'assets/img/survivor/perk/vigil.png'),
('Visionary', (SELECT id FROM Survivors WHERE name = 'Felix Richter'), 'assets/img/survivor/perk/visionary.png'),
('Wake Up!', (SELECT id FROM Survivors WHERE name = 'Quentin Smith'), 'assets/img/survivor/perk/wake_up.png'),
('We’ll Make It', NULL, 'assets/img/survivor/perk/well_make_it.png'),
('We’re Gonna Live Forever', (SELECT id FROM Survivors WHERE name = 'David King'), 'assets/img/survivor/perk/were_gonna_live_forever.png'),
('Wicked', (SELECT id FROM Survivors WHERE name = 'Sable Ward'), 'assets/img/survivor/perk/wicked.png'),
('Windows of Opportunity', (SELECT id FROM Survivors WHERE name = 'Kate Denson'), 'assets/img/survivor/perk/windows_of_opportunity.png'),
('Wiretap', (SELECT id FROM Survivors WHERE name = 'Ada Wong'), 'assets/img/survivor/perk/wiretap.png');